### PR TITLE
#32089 Removed manually created extension attributes

### PR DESCRIPTION
**Pull request by ProkopovVitaliy**
### Description (*)

Removed `Magento\InventoryApi\Api\Data\StockExtension` and `Magento\InventoryApi\Api\Data\StockExtensionInterface`. Replaced to use `Magento\Framework\Api\ExtensionAttributesInterface`.
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32089

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by coderimus** [comment]
@magento run all tests

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Comment by sdouma** [comment]
@magento run all tests

**Comment by sdouma** [comment]
@magento-engcom-team @ProkopovVitaliy 
Failing because the interface is returning \Magento\Framework\Api\ExtensionAttributesInterface? This is seems wrong unless architecture changes are coming. Can we just keep the stock extension interface and remove the methods?

**Pull request closed without merging**
