### PR TITLE
[Forwardport]MFTF tests refactoring.

### PR DESCRIPTION
**Pull request by nmalevanec**
### Fixed Issues (if relevant)

1. none.

### Manual testing scenarios (*)

1. none.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by nmalevanec** [comment]
@magento run integration tests

**Comment by nmalevanec** [comment]
@magento run Integration tests

**Comment by nmalevanec** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
Delivered in scope of https://github.com/magento/inventory/pull/2965

**Pull request closed without merging**
