### PR TITLE
MC-17983: Magento is not validating inventory while using custom options

### PR DESCRIPTION
**Pull request by o-iegorov**
### Description (*)
This is fix for an issue: Magento is not validating inventory while using custom options

### Manual testing scenarios (*)

Preconditions: 
Magento 2.3.1 (They are facing same in vanilla magento 2.3.1)

Steps to Reproduce: 
1. Create a simple product with Inventory = 1 (Saleable Quantity). 
2. Add a dropdown type Custom Option - Color with 3 options - red, blue, green and save the product. 
3. Now open PDP or PLP page and add 1 qty to cart with Red Option. After adding 1 qty product successfully, now again add 1 qty with Green option. 
4. It should not allow adding product to cart with green/blue option because there is only 1 salable quantity and product with red option already added to cart.

EXPECTED RESULTS:
It should not allow adding 2nd qty with different option to cart because salable qty is only 1.

ACTUAL RESULTS:
It is allowing to add product to cart with custom option which is not present in cart. 
For example it is allowing to add product with green option when red option exist in cart.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2408) <br/>All committers have signed the CLA.

**Review by novikor — APPROVED** [review]
Fine, - thank you for your contribution.
It would be even finer if we cover that case with integration tests.
@o-iegorov , what do you think about the suggestion?

**Comment by o-iegorov** [comment]
@novikor I have conversation with @ishakhsuvarov regarding tests, this issue will be covered by MFTF test

**Comment by novikor** [comment]
Fine.

**Comment by devzer01** [comment]
when using Magento add to cart API the qty represented is showing a sum of cart qty and requested qty, wrapping a max is causing an issue, can you please advice 

qty

**Pull request merged**
