### PR TITLE
Load product salability data on demand

### PR DESCRIPTION
**Pull request by novikor**
### Description (*)
Stop stock data load on afterload event.
Inheritance of #3039

See #3202

### Fixed Issues (if relevant)

1. #3201

### Manual testing scenarios (*)
No

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by novikor** [comment]
@magento run Static Tests

**Comment by novikor** [comment]
@magento run Integration Tests

**Comment by novikor** [comment]
@magento run Integration Tests

**Comment by novikor** [comment]
@magento run Static Tests

**Comment by swnsma** [comment]
@magento run all tests

**Pull request merged**
