### PR TITLE
Store pickup postcodes search: check if source is enabled

### PR DESCRIPTION
**Pull request by novikor**
Added check if the source is enabled

### Description (*)
There was no check if source is enabled for the search by postcode.
Now it is.

### Manual testing scenarios (*)
Not applicable.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2100) <br/>All committers have signed the CLA.

**Comment by novikor** [comment]
`Composer.json` was not updated because it already is in #2091

**Comment by ishakhsuvarov** [comment]
@novikor This PR might get merged sooner if `composer.json` is updated.

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by novikor** [comment]
I will do it.

**Comment by ishakhsuvarov** [comment]
@novikor It's all good, disregard my deleted comment :)

**Pull request merged**
