### PR TITLE
[TSG] MC-34514: [Backport for 2.3.x] Allow an authenticated user in custom role without permissons can edit sources

### PR DESCRIPTION
**Pull request by zakdma**
### Bug - P2
* [MC-34514](https://jira.corp.magento.com/browse/MC-34514) [Backport for 2.3.x] Allow an authenticated user in custom role without permissons can edit sources

### CE Checklist

- [ ] PR is green on M2 Quality Portal
- [ ] Jira issues have accurate summary, meaningful description and have links to relevant documentation at the story/task level
- [ ] Semantic Version build failure is approved by architect (if build is red) <Architect Name>
- [ ] Pull Request approved by architect <Architect Name>
- [ ] Pull Request quality review performed by <name>
- [ ] All unstable functional acceptance tests are isolated (if any)
- [ ] All linked Zephyr tests are approved by PO and have Ready to Use status
- [ ] Travis CI build is green (for mainline CE only)
- [ ] Jenkins Unit, Extended FAT CE, Extended FAT EE and Extended FAT B2B builds are green

### CODE REVIEW

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Comment by sidolov** [comment]
@magento run Functional Tests CE, Functional Tests EE, Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Pull request merged**
