### PR TITLE
MSI-2151+2152: [UI Love for Assigned Sources]

### PR DESCRIPTION
**Pull request by seruymt**
#2151  and #2152

I did it in Magento style. I think it will be better to use the familiar design.

sources_view

### CODE REVIEW

**Comment by novikor** [comment]
Hi, @seruymt .

Thank you for your contribution, well done.

Please merge the conflicts with `2.3-develop`.

**Review by novikor — DISMISSED** [review]
Hi, @seruymt .

Thank you for your contribution, well done.

Please resolve the conflicts with 2.3-develop.

**Comment by ishakhsuvarov** [comment]
Whole functional tests suite must be executed prior to merging the PR. Most likely some of the tests would have to be adjusted as a result of this change.

**Comment by novikor** [comment]
@ishakhsuvarov , any updates about functional tests suite execution?
As I remember, you have created an internal ticket for that.

**Comment by ishakhsuvarov** [comment]
@novikor Apparently functional tests were good enough to support this change without failing.

**Review by ishakhsuvarov — APPROVED** [review]

**Pull request merged**
