### PR TITLE
MC-38590: "Out of Stock" Configurable Product Shows Up on Storefront …

### PR DESCRIPTION
**Pull request by nikita-shcherbatykh**
…Category Page

### Description (*)

Filtering not taking stock sources/reservations into account

Steps to reproduce:

Create additional source assigned to additional stock. Assign created stock to Main Website.
Create configurable product with two variations. Assign configurable product to category.
Verify configurable product is visible on storefront category page and has 'In Stock' status.
Navigate back to admin area and disable one configurable variation and set to 'Out of Stock' another one.
Verify configurable product on storefront category page.
 

EXPECTED RESULTS:
Configurable product is not visible on storefront category page.

 

ACTUAL RESULTS:
Configurable product presents on storefront category page, despite it has 'Out of Stock' status.
### Fixed Issues (if relevant)

1. Fixes magento/inventory#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by viktym** [comment]
@magento import pr to magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@viktym the pull request successfully imported.

**Comment by viktym** [comment]
@magento import pr to magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@viktym, an error occurred during the Pull Request import.

**Comment by viktym** [comment]
@magento import pr to magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@viktym, an error occurred during the Pull Request import.

**Pull request closed without merging**
