### PR TITLE
MC-37718: Grouped product remains In Stock On Mass Update

### PR DESCRIPTION
**Pull request by nikita-shcherbatykh**
### Related Pull Requests
- https://github.com/magento-tsg-csl3/magento2ce/pull/531

### Description (*)
Steps to reproduce:
Create two simple products with stock.
Create Grouped product and assign two previously created simple products.
select 2 simple prod, Actions> click on Update attribute.
click on tab2 advanced inventory.uncheck the box for qty "0" and save
Run bin/magento cron:run
Actual Res: Stock status = "In stock" 
Expected: Stock Status = "Out of stock"

### Fixed Issues (if relevant)

1. Fixes magento/inventory#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nikita-shcherbatykh** [comment]
@magento run all tests

**Comment by nikita-shcherbatykh** [comment]
@magento run all tests

**Comment by nikita-shcherbatykh** [comment]
@magento run all tests

**Comment by tsviklinskyi** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@sidolov the pull request successfully imported.

**Pull request closed without merging**
