### PR TITLE
[TSG] MC-34515: Allow  an authenticated user in custom role without permissons can edit sources

### PR DESCRIPTION
**Pull request by zakdma**
### Bug - P2
* [MC-34515](https://jira.corp.magento.com/browse/MC-34515) Allow  an authenticated user in custom role without permissons can edit sources

### CE Checklist

- [ ] PR is green on M2 Quality Portal
- [ ] Jira issues have accurate summary, meaningful description and have links to relevant documentation at the story/task level
- [ ] Semantic Version build failure is approved by architect (if build is red) <Architect Name>
- [ ] Pull Request approved by architect <Architect Name>
- [ ] Pull Request quality review performed by <name>
- [ ] All unstable functional acceptance tests are isolated (if any)
- [ ] All linked Zephyr tests are approved by PO and have Ready to Use status
- [ ] Travis CI build is green (for mainline CE only)
- [ ] Jenkins Unit, Extended FAT CE, Extended FAT EE and Extended FAT B2B builds are green

### CODE REVIEW

**Comment by zakdma** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run Integration Tests, Functional Tests B2B

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@zakdma I have fould fatal error in the logs that caused the Integration tests build failure, maybe it will be helpful for you: 
```
12:28:16 [Integration-11-ce] .PHP Fatal error:  Uncaught InvalidArgumentException: Invalid scope type 'stores' in /var/www/html/lib/internal/Magento/Framework/App/ScopeResolverPool.php:40
12:28:16 [Integration-11-ce] Stack trace:
12:28:16 [Integration-11-ce] #0 /var/www/html/lib/internal/Magento/Framework/App/Config/ScopeCodeResolver.php(48): Magento\Framework\App\ScopeResolverPool->get()
12:28:16 [Integration-11-ce] #1 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/App/Config.php(80): Magento\Framework\App\Config\ScopeCodeResolver->resolve()
12:28:16 [Integration-11-ce] #2 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/App/MutableScopeConfig.php(50): Magento\TestFramework\App\Config->setValue()
12:28:16 [Integration-11-ce] #3 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/ConfigFixture.php(118): Magento\TestFramework\App\MutableScopeConfig->setValue()
12:28:16 [Integration-11-ce] #4 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/ConfigFixture.php(95): Magento\TestFramework\Annotation\ConfigFixture->setScopeConfigValue()
12:28:16 [Integration-11-ce] #5 /var/www/html/dev/tests/integration/framework/Magento/TestFramework/Annotation/ConfigFixture.php(186 in /var/www/html/lib/internal/Magento/Framework/App/ScopeResolverPool.php on line 40
```

**Comment by zakdma** [comment]
@sidolov I suppose it's because we run tests with 2.4.1-develop core branches because this bug is security one. But there is no security branches for Inventory like core 2.4.1-develop.

**Comment by sidolov** [comment]
@zakdma according to the build parameters it was run with Magento 2.4-develop.

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by engcom-Delta** [comment]
:heavy_check_mark: QA passed
**Before:**
#3132Main

**After:**
#3132PR

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
- [x] File conflicts test failures not related to PR changes and should be resolved in scope of https://github.com/magento/adobe-stock-integration/pull/1598

**Pull request merged**
