### PR TITLE
MSI-1262: The stock item was unable to be saved. Please try again.

### PR DESCRIPTION
**Pull request by kisroman**
### Fixed Issues (if relevant)

1. https://github.com/magento-engcom/msi/issues/1262

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=1264) <br/>All committers have signed the CLA.

**Comment by maghamed** [comment]
hey @kisroman ! great that you pointed out this issue and created PR to fix one 
unfortunately current PR can't be merged because you introduce back dependency on Inventory module on InventoryAdminUi  (which is logically wrong).

What we need to do is untie 
InventoryImportExport and Inventory modules from necessity to depend on InventoryAdminUi

Look at the analog approach proposed by @seruymt  
https://github.com/magento-engcom/msi/pull/1265/files

**Comment by kisroman** [comment]
@maghamed, ok. So I am closing this PR.

**Comment by djixas** [comment]
When will this be fixed?

**Pull request closed without merging**
