### PR TITLE
Fixes inventory sales BackOrderNotifyCustomerConditionTest.php local failure

### PR DESCRIPTION
**Pull request by engcom-Golf**
### Description (*)

run \Magento\InventorySales\Test\Unit\Model\IsProductSalableCondition\BackOrderNotifyCustomerConditionTest causes warnings

### Fixed Issues (if relevant)

1. No issues created

### Manual testing scenarios (*)

1. No manual testing required

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by engcom-Golf** [comment]
@magento run all tests

**Comment by engcom-Golf** [comment]
@magento run Functional Tests EE, Functional Tests B2B

**Comment by gabrieldagama** [comment]
@magento import pr to magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@gabrieldagama the pull request successfully imported.

**Comment by gabrieldagama** [comment]
Merged to 2.4.2 https://github.com/magento-commerce/inventory/pull/44 - will be merged back soon.

**Pull request closed without merging**
