### PR TITLE
MSI-3022: Refactor tests to be able to execute them when Magento performance is dropped.

### PR DESCRIPTION
**Pull request by nmalevanec**
### Fixed Issues (if relevant)

1. https://github.com/magento/inventory/issues/3022: Refactor tests to be able to execute them when Magento performance is dropped

### Manual testing scenarios (*)

1. none.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by nmalevanec** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by nmalevanec** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by nmalevanec** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by nmalevanec** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by nmalevanec** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by zakdma** [comment]
@nmalevanec @sidolov @okolesnyk please use CliConsumerStartActionGroup instead of directly run consumers using CLI

**Comment by nmalevanec** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Pull request merged**
