### PR TITLE
Issue #2138: PHTML implementation of Advanced Inventory tab in product mass update refactored using UI components

### PR DESCRIPTION
**Pull request by fratob85**
PHTML implementation of Advanced Inventory tab in product mass update refactored using UI components.
Added fields conditional visibility on manage stock.

### Description (*)

PHTML implementation of Advanced Inventory tab in product mass update refactored using UI components.
Added fields conditional visibility on manage stock.

### Fixed Issues (if relevant)

1. https://github.com/magento-engcom/msi/issues/2138 : Disable fields in Mass action -> Update attributes -> Advanced inventory

### Manual testing scenarios (*)

1. Select multiple products in the in the Magento Backend Catalog
2. In the Action combo, select "Update Attributes"
3. The changes will be displayed in "Advanced Inventory" tab

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by maghamed** [comment]
hey @fratob85 could you please look at broken Integration test - https://travis-ci.org/magento-engcom/msi/jobs/520422652

**Comment by malesh-v** [comment]
I have clear Magento without sources.

Steps to reproduce :
1. I create 2 simple products
2. I select their, click **Update Attributes**
3. Open **Advanced Inventory** tab
AR : There should be fields _Qty_, _Notify for Quantity Below_ and _Stock Avaibility_

These fields should be hidden only if multi sources are enabled.

**Review by ishakhsuvarov — CHANGES_REQUESTED** [review]
* Please move the UI Component changes to the `magento/magento2` repository as a separate PR
* Update this PR to keep only MSI related changes, specifically hiding the fields when multiple sources are enabled

**Comment by malesh-v** [comment]
Also, I found that changes in the next fields don't apply to selected products : 

image

**Comment by fratob85** [comment]
I'm already working on it. I hope to send the new pull requests in a short time. Thanks for the comments.

**Comment by fratob85** [comment]
@vad1m777  I tested the mass Update attributes procedure in the 2.3-develop branch of Magento-MSI. The problem of partial data saving appears to be already existing, thus it seems to be not related to my Pull Request.
Can you please verify? Thanks in advance.

**Comment by smoskaluk** [comment]
Hi @fratob85 , on the 2.3-develop with MSI I was able update only "Qty use decimals" field through Mass action -> Update attributes -> Advanced inventory

**Comment by ishakhsuvarov** [comment]
Hi @fratob85 
Are you still interested in this PR? Is there anything we can help you with?

**Comment by ishakhsuvarov** [comment]
Hi @fratob85 
I'm closing this PR for now as there are already some conflicts in the code and it seems to be inactive at the moment. Please let us know if you feel like continuing this and we will happily reopen.

Thanks!

**Pull request closed without merging**
