### PR TITLE
Fix Error in Checkout when switching from Store-Pickup to Shipping

### LINKED ISSUE #3216: Error in Checkout when switching from Store-Pickup to Shipping
### Preconditions (*)
1. Magento 2.4.0 with sample data (clean installation)
2. Inventory 1.2.0

### Steps to reproduce (*)
1. Create 1 or more new sources with `Use as Pickup Location` option enabled in it.
2. Create new stock for default website using newly created sources
3. Assign products to newly created sources and add inventory in it so it can be available for pickup.
4. Enable In store Delivery shipping method from Store Config/Sales/Delivery Methods (and at least one other method)
5. Login with account with at least one (1) default shipping address
5. Add product to cart
6. View cart, select `In-Store Pickup` in shipping estimate, and proceed to checkout
7. Switch from `Pick In Store` to `Shipping`

### Expected result (*)
1. Default shipping address should be selected
2. no errors in console
3. able to proceed to payment step

### Actual result (*)
1. Error in console
```
rules.js:69 Uncaught TypeError: Cannot read property 'length' of null
    at Object.handler (rules.js:69)
    at validate (validator.js:44)
    at validator.js:84
    at Function._.every._.all (underscore.js:237)
    at validator (validator.js:82)
    at UiClass.validate (abstract.js:406)
    at UiClass.onUpdate (abstract.js:431)
    at Function.notifySubscribers (knockout.js:1320)
    at Function.valueHasMutated (knockout.js:1538)
    at UiClass.observable [as value] (knockout.js:1504)
    ...
```
2. unable to proceed to payment step

### Notes
~~My initial guess is the error has to do with new address form, as the stack trace mentions validate and ui form/element/abstract.~~
Edit: It seems to be an issue with setting the shipping address when switching methods, as even trying to enter a new address:
- add new address via popup (if it lets you)
- switching to store pickup and switching back (even without having selected a store)

Overall the implementation here is very buggy and needs significant work to get it working.

Also, if you return to the shopping cart (regardless of method) and proceed to checkout again, only the sidebar loads and the same error is presented in the console. You need to log out and log back in to be able to load the checkout fully again.

### PR DESCRIPTION
**Pull request by LyraGhost**
### Description (*)
The issue encountered caused the Checkout to break until user signed out.
All fixes were contained within a single file: `InventoryInStorePickupFrontend/view/frontend/web/js/view/store-pickup.js`

Fixes issue:
- When clicking the `Shipping` tab to switch away from store pickup, the `checkoutProvider` shipping address was being set to the current value of `quote.shippingAddress()`, which would be a store location if one was selected, or another user shipping address if not. (this wasn't causing an issue, but was not changing anything)
- `checkoutProvider.trigger('data.reset')` was also being called, which is what triggered the error (described in linked issue) and caused the checkout to break.
- Changed second line of `selectShippingMethod` from setting shipping-address (redundantly) to second method necessary for setting shipping-method, as used in [Checkout/js/view/shipping.js](https://github.com/magento/magento2/blob/2.4-develop/app/code/Magento/Checkout/view/frontend/web/js/view/shipping.js#L243).

Other changes:
- Removed redundant function `convertAddressType` which was repeating tasks done in `js/model/pickup-locations-service.js`.
- Added saving of last used (non-pickup) shipping address, which is restored when switching back to `Shipping` tab.

### Fixed Issues (if relevant)
1. Fixes magento/inventory#3216

### Manual testing scenarios (*)
Same as linked issue steps to reproduce.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by LyraGhost** [comment]
@magento run all tests

**Comment by LyraGhost** [comment]
@magento run all tests

**Comment by LyraGhost** [comment]
@magento run all tests

**Comment by LyraGhost** [comment]
@magento run all tests

**Comment by swnsma** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by LyraGhost** [comment]
@magento run Functional Tests B2B

**Comment by LyraGhost** [comment]
@magento run all tests

**Comment by LyraGhost** [comment]
@magento run Functional Tests B2B, Functional Tests CE

**Comment by LyraGhost** [comment]
@magento run Functional Tests B2B, Functional Tests EE

**Comment by LyraGhost** [comment]
@magento run all tests

**Comment by LyraGhost** [comment]
Haven't had a chance to test if the recent changes to `InventoryInStorePickupFrontend/view/frontend/web/js/view/store-pickup.js` fix the original issue and/or if it conflicts with my fixes.
I'll update here when I get a chance to test it.

**Comment by ganeddact** [comment]
I was trying to test this PR, but the JS fails.

On line 255 in the changed file I see: 
            this.convertAddressType(quote.shippingAddress());
This should be probably be changed, convertAddressType is not present anymore

**Pull request closed without merging**
