### PR TITLE
Singular names switched to plural in webapi calls.

### PR DESCRIPTION
**Pull request by phoenix128**
### Description
Usage of plural names in web api calls.

### Fixed Issues (if relevant)
1. magento/msi#1286: Fix singular names on plurals in Web API service URLs to comply with RESTful practices for all MSI modules

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Review by TomashKhamlai — CHANGES_REQUESTED** [review]
Tests are failing now because of these changes. Please check and correct next lines:

https://github.com/magento-engcom/msi/blob/9238f266916294fb98b7a82a2ad5dc052c5af268/app/code/Magento/InventoryCatalog/Test/Api/GetDefaultSourceTest.php#L37

https://github.com/magento-engcom/msi/blob/9238f266916294fb98b7a82a2ad5dc052c5af268/app/code/Magento/InventoryCatalogApi/Test/Api/PreventDefaultSourceDisablingTest.php#L22

https://github.com/magento-engcom/msi/blob/9238f266916294fb98b7a82a2ad5dc052c5af268/app/code/Magento/InventoryApi/Test/Mftf/Metadata/source-meta.xml#L12

**Comment by maghamed** [comment]
That's current web api test report
```
[1;34mRunning MSI testsuite...[0m
PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

.....................EEF.FE.....E................FFFF............................E...F.F........F                                                                                                                              97 / 97 (100%)E

Time: 2.48 minutes, Memory: 142.00MB

There were 6 errors:

1) Magento\InventoryApi\Test\Api\SourceRepository\CarrierLinkManagementTest::testCarrierLinksManagement with data set "add_carrier_new_links" (array(array('ups', 100), array('usps', 200), array('dhl', 300), array('fedex', 400)))
Exception: {"message":"Validation Failed","errors":[{"message":"You can't configure \"%field\" because you have chosen Global Shipping configuration.","parameters":{"field":"carrier_links"}}]}

/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:133
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:85
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/RestClient.php:106
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:102
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:176
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php:115
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php:40

2) Magento\InventoryApi\Test\Api\SourceRepository\CarrierLinkManagementTest::testCarrierLinksManagement with data set "replace_carrier_links" (array(array('dhl', 100), array('fedex', 200)))
Exception: {"message":"Validation Failed","errors":[{"message":"You can't configure \"%field\" because you have chosen Global Shipping configuration.","parameters":{"field":"carrier_links"}}]}

/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:133
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:85
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/RestClient.php:106
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:102
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:176
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php:115
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php:40

3) Magento\InventoryApi\Test\Api\SourceRepository\CreateTest::testCreate
Exception: {"message":"Validation Failed","errors":[{"message":"You can't configure \"%field\" because you have chosen Global Shipping configuration.","parameters":{"field":"carrier_links"}}]}

/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:133
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:66
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/RestClient.php:83
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:99
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:176
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/CreateTest.php:68

4) Magento\InventoryApi\Test\Api\SourceRepository\UpdateTest::testUpdate
Exception: {"message":"Validation Failed","errors":[{"message":"You can't configure \"%field\" because you have chosen Global Shipping configuration.","parameters":{"field":"carrier_links"}}]}

/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:133
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:85
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/RestClient.php:106
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:102
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:176
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/UpdateTest.php:69

5) Magento\InventoryCatalog\Test\Api\GetDefaultSourceTest::testGetDefaultSource
Exception: {"message":"Request does not match any route."}

/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:133
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:31
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/RestClient.php:60
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:96
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:176
/var/www/html/msi/app/code/Magento/InventoryCatalog/Test/Api/GetDefaultSourceTest.php:46

6) Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest::testSourceSelectionService
Exception: {"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/446440188059"}]}}

/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:133
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/HttpClient/CurlClient.php:66
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest/RestClient.php:83
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/Webapi/Adapter/Rest.php:99
/var/www/html/msi/dev/tests/api-functional/framework/Magento/TestFramework/TestCase/WebapiAbstract.php:176
/var/www/html/msi/app/code/Magento/InventorySourceSelectionApi/Test/Api/SourceSelectionServiceTest.php:103

--

There were 9 failures:

1) Magento\InventoryApi\Test\Api\SourceRepository\CarrierLinkManagementTest::testCarrierLinksManagement with data set "delete_carrier_links" (array())
Failed asserting that true matches expected 0.

/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php:46

2) Magento\InventoryApi\Test\Api\SourceRepository\CarrierLinkManagementTest::testCarrierLinksValidation with data set "carrier_codes_not_exits" (array('source-code-1', 'source-name-1', 'source-postcode', 'US', 0, array(array('no_exists_1', 100), array('no_exists_2', 200))), array('Validation Failed', array(array('Carrier with code: "%carrier"...xists.', array('no_exists_1')), array('Carrier with code: "%carrier"...xists.', array('no_exists_2')))))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'message' => 'Validation Failed'
     'errors' => Array (
         0 => Array (
-            'message' => 'Carrier with code: "%carrier" don't exists.'
+            'message' => 'You can't configure "%field" because you have chosen Global Shipping configuration.'
             'parameters' => Array (
-                'carrier' => 'no_exists_1'
+                'field' => 'carrier_links'
             )
         )
-        1 => Array (...)
     )
 )

/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/CarrierLinkManagementTest.php:169

3) Magento\InventoryApi\Test\Api\SourceRepository\ValidationTest::testFailedValidationOnUpdate with data set "null_source_code" ('source_code', null, array('Validation Failed', array(array('"%field" can not be empty.', array('source_code')))))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'message' => 'Validation Failed'
-    'errors' => Array (...)
+    'message' => ''
 )

/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/ValidationTest.php:380
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/ValidationTest.php:156

4) Magento\InventoryApi\Test\Api\SourceRepository\ValidationTest::testFailedValidationOnUpdate with data set "empty_source_code" ('source_code', '', array('Validation Failed', array(array('"%field" can not be empty.', array('source_code')))))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'message' => 'Validation Failed'
-    'errors' => Array (...)
+    'message' => ''
 )

/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/ValidationTest.php:380
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/ValidationTest.php:156

5) Magento\InventoryApi\Test\Api\SourceRepository\ValidationTest::testFailedValidationOnUpdate with data set "whitespaces_source_code" ('source_code', ' ', array('Validation Failed', array(array('"%field" can not be empty.', array('source_code')))))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'message' => 'Validation Failed'
-    'errors' => Array (...)
+    'message' => ''
 )

/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/ValidationTest.php:380
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/ValidationTest.php:156

6) Magento\InventoryApi\Test\Api\SourceRepository\ValidationTest::testFailedValidationOnUpdate with data set "with_whitespaces_source_code" ('source_code', 'source code', array('Validation Failed', array(array('"%field" can not contain whitespaces.', array('source_code')))))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'message' => 'Validation Failed'
-    'errors' => Array (...)
+    'message' => ''
 )

/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/ValidationTest.php:380
/var/www/html/msi/app/code/Magento/InventoryApi/Test/Api/SourceRepository/ValidationTest.php:156

7) Magento\InventoryCatalog\Test\Api\StockSourceLink\PreventAssignSourcesToDefaultStockTest::testAssignSourcesToStockWithWrongParameters with data set "multiple_sources_assigned_to_default_stock" (array('default', 'eu-2'), 1, array('Validation Failed', array(array('Can not save link related to ... Stock', array()), array('Can not save link related to ... Stock', array()))))
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'message' => 'Validation Failed'
     'errors' => Array (
         0 => Array (...)
-        1 => Array (...)
     )
 )

/var/www/html/msi/app/code/Magento/InventoryCatalog/Test/Api/StockSourceLink/PreventAssignSourcesToDefaultStockTest.php:62

8) Magento\InventoryCatalogApi\Test\Api\PreventDefaultSourceDisablingTest::testPreventDefaultSourceDisabling
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    'message' => 'Validation Failed'
-    'errors' => Array (...)
+    'message' => 'Request does not match any route.'
 )

/var/www/html/msi/app/code/Magento/InventoryCatalogApi/Test/Api/PreventDefaultSourceDisablingTest.php:88
/var/www/html/msi/app/code/Magento/InventoryCatalogApi/Test/Api/PreventDefaultSourceDisablingTest.php:71

9) Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest::testSourceSelectionService
PHPUnit\Framework\Exception: Error in fixture: "\/var\/www\/html\/msi\/dev\/tests\/integration\/testsuite\/..\/..\/..\/..\/app\/code\/Magento\/InventoryApi\/Test\/_files\/source_items.php".
 SQLSTATE[HY000]: General error: 1412 Table definition has changed, please retry transaction, query was: DELETE FROM `inventory_stock_10` WHERE (sku IN ('SKU-1', 'SKU-3', 'SKU-4'))
 #0 /var/www/html/msi/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/html/msi/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/html/msi/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/html/msi/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `in...', Array)
#4 /var/www/html/msi/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(540): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `in...', Array)
#5 /var/www/html/msi/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(614): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('DELETE FROM `in...', Array)
#6 /var/www/html/msi/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(664): Magento\Framework\DB\Adapter\Pdo\Mysql->query('DELETE FROM `in...')
#7 /var/www/html/msi/app/code/Magento/InventoryIndexer/Indexer/IndexHandler.php(80): Zend_Db_Adapter_Abstract->delete('inventory_stock...', '(sku IN ('SKU-1...')
#8 /var/www/html/msi/app/code/Magento/InventoryIndexer/Indexer/SourceItem/SourceItemIndexer.php(136): Magento\InventoryIndexer\Indexer\IndexHandler->cleanIndex(Object(Magento\InventoryMultiDimensionalIndexerApi\Model\IndexName), Object(ArrayIterator), 'default')
#9 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer->executeList(Array)
#10 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer\Interceptor->___callParent('executeList', Array)
#11 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer\Interceptor->Magento\Framework\Interception\{closure}(Array)
#12 /var/www/html/msi/generated/code/Magento/InventoryIndexer/Indexer/SourceItem/SourceItemIndexer/Interceptor.php(52): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer\Interceptor->___callPlugins('executeList', Array, Array)
#13 /var/www/html/msi/app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAfterSourceItemsSavePlugin.php(54): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer\Interceptor->executeList(Array)
#14 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(146): Magento\InventoryIndexer\Plugin\InventoryApi\ReindexAfterSourceItemsSavePlugin->afterExecute(Object(Magento\Inventory\Model\SourceItem\Command\SourceItemsSave\Interceptor), NULL, Array)
#15 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Inventory\Model\SourceItem\Command\SourceItemsSave\Interceptor->Magento\Framework\Interception\{closure}(Array)
#16 /var/www/html/msi/generated/code/Magento/Inventory/Model/SourceItem/Command/SourceItemsSave/Interceptor.php(26): Magento\Inventory\Model\SourceItem\Command\SourceItemsSave\Interceptor->___callPlugins('execute', Array, Array)
#17 /var/www/html/msi/app/code/Magento/InventoryApi/Test/_files/source_items.php(83): Magento\Inventory\Model\SourceItem\Command\SourceItemsSave\Interceptor->execute(Array)
#18 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(173): require('/var/www/html/m...')
#19 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(203): Magento\TestFramework\Annotation\DataFixture->_applyOneFixture('/var/www/html/m...')
#20 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(91): Magento\TestFramework\Annotation\DataFixture->_applyFixtures(Array)
#21 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTransaction(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#22 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#23 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(96): Magento\TestFramework\EventManager->fireEvent('startTransactio...', Array)
#24 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(81): Magento\TestFramework\Event\Transaction->_startTransaction(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#25 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(46): Magento\TestFramework\Event\Transaction->_processTransactionRequests('startTest', Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#26 [internal function]: Magento\TestFramework\Event\Transaction->startTest(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#27 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#28 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(126): Magento\TestFramework\EventManager->fireEvent('startTest', Array)
#29 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestResult.php(395): Magento\TestFramework\Event\PhpUnit->startTest(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#30 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestResult.php(637): PHPUnit\Framework\TestResult->startTest(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#31 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#32 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#33 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#34 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#35 /var/www/html/msi/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#36 /var/www/html/msi/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#37 /var/www/html/msi/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#38 /var/www/html/msi/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#39 {main}

/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php:176
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php:203
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php:91
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/EventManager.php:49
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php:96
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php:81
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php:46
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/EventManager.php:49
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php:126

/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php:100
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php:81
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php:46
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/EventManager.php:49
/var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php:126

ERRORS!
Tests: 97, Assertions: 384, Errors: 6, Failures: 9.

=== Memory Usage System Stats ===
Memory usage (OS):	177.37M (128.53% of 138.00M reported by PHP)
Estimated memory leak:	39.37M (22.20% of used memory)


```

**Comment by phoenix128** [comment]
@maghamed , I fixed the wrong URLs. All the other errors are caused by an issue i fixed here in the core: https://github.com/magento/magento2/pull/16137 .

**Review by TomashKhamlai — APPROVED** [review]

**Comment by maghamed** [comment]
#1286

**Pull request merged**
