### PR TITLE
Sync with mainline 2.3-develop

### PR DESCRIPTION
**Pull request by ishakhsuvarov**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2395) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2395) before we can accept your contribution.<br/>**2** out of **16** committers have signed the CLA.<br/><br/>:white_check_mark: fascinosum<br/>:white_check_mark: tomreece<br/>:x: danmooney2<br/>:x: danielrenaud<br/>:x: dthampy<br/>:x: Roman Lytvynenko<br/>:x: irenelagno<br/>:x: magento-cicd2<br/>:x: lenaorobei<br/>:x: odubovyk<br/>:x: UlyanaKiklevich<br/>:x: yuriichayka<br/>:x: dhorytskyi<br/>:x: cpartica<br/>:x: MilaLesechko<br/>:x: magento-engcom-team<hr/>**Roman Lytvynenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests build

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2395) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2395) before we can accept your contribution.<br/>**1** out of **15** committers have signed the CLA.<br/><br/>:white_check_mark: tomreece<br/>:x: danmooney2<br/>:x: danielrenaud<br/>:x: dthampy<br/>:x: Roman Lytvynenko<br/>:x: irenelagno<br/>:x: magento-cicd2<br/>:x: lenaorobei<br/>:x: odubovyk<br/>:x: UlyanaKiklevich<br/>:x: yuriichayka<br/>:x: dhorytskyi<br/>:x: cpartica<br/>:x: MilaLesechko<br/>:x: magento-engcom-team<hr/>**Roman Lytvynenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2395) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2395) before we can accept your contribution.<br/>**1** out of **14** committers have signed the CLA.<br/><br/>:white_check_mark: swnsma<br/>:x: nirmalraval18<br/>:x: magento-engcom-team<br/>:x: kazim-krish<br/>:x: sarfarazbheda<br/>:x: manishgoswamij<br/>:x: viktym<br/>:x: nikita-shcherbatykh<br/>:x: DianaRusin<br/>:x: ankurvr<br/>:x: Stas Puga<br/>:x: bobemoe<br/>:x: lpouwelse<br/>:x: pmclain<hr/>**Stas Puga** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Pull request closed without merging**
