### PR TITLE
Mc 17139

### PR DESCRIPTION
**Pull request by dhaecker**
### Bug
* [MC-16318](https://jira.corp.magento.com/browse/MC-16318) Flaky MFTF Test: MAGETWO-93965: creating scheduled update for staging dashboard with max year value
* [MC-16976](https://jira.corp.magento.com/browse/MC-16976) Flaky MFTF Test: MC-14748: Validate product special price after update
* [MC-17139](https://jira.corp.magento.com/browse/MC-17139) Multiple Unstable MFTF Tests The Are Slowing Down PRs

### Related Pull Requests
https://github.com/magento/magento2ce/pull/4314
https://github.com/magento/magento2ee/pull/1751
https://github.com/magento/magento2b2b/pull/746

### Checklist
- [ ] PR is green on M2 Quality Portal
- [ ] Jira issues have accurate summary, meaningful description and have links to relevant documentation at the story/task level
- [ ] Semantic Version build failure is approved by architect (if build is red) <Architect Name>
- [ ] Pull Request approved by architect <Architect Name>
- [ ] Pull Request quality review performed by <name>
- [ ] All unstable functional acceptance tests are isolated (if any)
- [ ] All linked Zephyr tests are approved by PO and have Ready to Use status
- [ ] Travis CI build is green (for mainline CE only)
- [ ] Jenkins Extended FAT build is green

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2303) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2303) before we can accept your contribution.<br/>

**Comment by ishakhsuvarov** [comment]
Hi @dhaecker 

Looks like the files changed relate not only to MSI modules but to the bunch of core modules as well. It would be best if you could only deliver MSI related tests to this repository as core modules are here just for developer experiences and synced with mainline when needed.

Thanks

**Comment by dhaecker** [comment]
> Hi @dhaecker
> 
> Looks like the files changed relate not only to MSI modules but to the bunch of core modules as well. It would be best if you could only deliver MSI related tests to this repository as core modules are here just for developer experiences and synced with mainline when needed.
> 
> Thanks

@ishakhsuvarov I was unaware of how this repository was setup so I made my changes to the tests that I figured were being executed (made the same changes to CE & MSI test files). Knowing that the files are the same in both repos, is your request necessary for this PR or a best practice suggestion going forward (since CE & MSI tests contain the same changes in my branches, there should be no issues syncing after this PR)?

If you'd like me to make the changes for this PR before merging, please let me know which modules are MSI modules & i'll remove all my other changes. Thank you

**Comment by ishakhsuvarov** [comment]
MSI modules are the ones having name starting with `Inventory`.

Looks like this PR contains only 2 related tests:
* `Magento/Inventory/Test/Mftf/Test/AdminUseDecimalQuantityOnSimpleProductTest.xml`
* `Magento/Inventory/Test/Mftf/Test/AdminUseDecimalQuantityOnVirtualProductTest.xml`

It would be great to force push the PR with only 1 commit affecting these 2 files, otherwise we woulf be getting weird change history in this repo.

I can do that for you, if you can confirm that I've identified the correct tests.

**Comment by dhaecker** [comment]
> * AdminUseDecimalQuantityOnVirtualProductTest

@ishakhsuvarov In addition to those 2 tests that you identified, there are 8 other files that are changed in the InventoryAdminUi module. These are also MSI, correct? If so, then there should be 10 total files that need to be in this PR

Assistance with the force push would be helpful, thank you!

**Comment by ishakhsuvarov** [comment]
@dhaecker I've cleaned up the commit and force-pushed branch. Please let me know if it's good to go from your perspective and I'll merge it whenever you are ready.

Also, I see there are some internal tickets linked to the skipped tests, it'd be great if some note is left on those to make sure MSI is not left out when tickets are worked on.

Thanks

**Comment by dhaecker** [comment]
> @dhaecker I've cleaned up the commit and force-pushed branch. Please let me know if it's good to go from your perspective and I'll merge it whenever you are ready.
> 
> Also, I see there are some internal tickets linked to the skipped tests, it'd be great if some note is left on those to make sure MSI is not left out when tickets are worked on.
> 
> Thanks

@ishakhsuvarov everything looks gtg! Please merge whenever you get a chance. Yes there is an email chain w/ all of the managers w/ teams that run MFTF builds, a wiki page w/ all these skipped tests (plus the core ones), and bug tickets that will be distributed out w/ the expectation that ALL tests (including MSI) must be fixed & unskipped

**Pull request merged**
