### PR TITLE
add qty check for order items

### LINKED ISSUE #38063: Magento Community Edition: Version 2.4.7-beta1 - Create Partial Shipment with default magento MSI feature
### Preconditions and environment

- Magento Community Edition '2.4.7-beta1' without sample data is installed.
- Website have products
- Wants to create partial shipment for the order

### Steps to reproduce

1. Login into admin > Sales > Orders > Open order which have multiple products(items)
2. Create shipment for product1 (let's assume i have added Test simple, Test simple 2, Test simple 3 into cart, place an order, Login into admin > Sales > Orders > Open order, shipment created for product1 - http://i.imgur.com/q0Kg9L4.png 
3. Once shipment created for Test simple, again create new shipment for rest of two products.
4. what i am doing, if you will create another(2nd) shipment, you can see Test simple product into **Items Ordered** grid - http://i.imgur.com/a4PUxeO.png
5. when you select source, qty for ship is 0 for Test simple product, But i am able to add Qty to deduct value, while i add 1 into qty to deduct field for Test simple product, add 0 value for rest of 2 product, click on create shipment button, items to ship section not have information about the product, new shipment page looks like as per image - http://i.imgur.com/8i8bKxN.png
6. Rest of fields leave as it is.

### Expected result

New shipment creation page: 'items to ship' section doesn't have product information, also if we already created shipment for that product1, then it's doesn't move into next step which is new shipment page.

### Actual result

New shipment creation page: 'items to ship' section doesn't have product information - http://i.imgur.com/8i8bKxN.png

### Additional information

https://www.awesomescreenshot.com/video/21491584?key=165c1950b5dd5cba072517ca3650fc78

### Release note

_No response_

### Triage and priority

- [X] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [X] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by ejaz-alam**
### Description (*)

Steps to reproduce

1. Login into admin > Sales > Orders > Open order which have multiple products(items)
2. Create shipment for product1 (let's assume i have added Test simple, Test simple 2, Test simple 3 into cart, place an order, Login into admin > Sales > Orders > Open order, shipment created for product1 - http://i.imgur.com/q0Kg9L4.png
3. Once shipment created for Test simple, again create new shipment for rest of two products.
4. what i am doing, if you will create another(2nd) shipment, you can see Test simple product into Items Ordered grid - http://i.imgur.com/a4PUxeO.png
5. when you select source, qty for ship is 0 for Test simple product, But i am able to add Qty to deduct value, while i add 1 into qty to deduct field for Test simple product, add 0 value for rest of 2 product, click on create shipment button, items to ship section not have information about the product, new shipment page looks like as per image - http://i.imgur.com/8i8bKxN.png
6. Rest of fields leave as it is.

### Fixed Issues (if relevant)

1. Fixes magento/magento2#38063

## Before Fix
image

## After Fix

image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] README.md files for modified modules are updated and included in the pull request if any [README.md predefined sections](https://github.com/magento/devdocs/wiki/Magento-module-README.md) require an update
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ejaz-alam** [comment]
@ihor-sviziev please review.

**Comment by ejaz-alam** [comment]
@bgorski pls review.

**Review by engcom-Hotel — CHANGES_REQUESTED** [review]
Hello @ejaz-alam,

Thanks for the contribution!

PR changes looks good to me, but can you please cover the changes with some automated tests.

Thanks

**Comment by abhattGlo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run all tests

**Comment by engcom-Echo** [comment]
@magento run Functional Tests CE

**Comment by engcom-Echo** [comment]
@ejaz-alam Internal Team is working on it and added automated test coverage along with theses changes.

**Comment by engcom-Bravo** [comment]
Hi @ejaz-alam,

Thanks for the collaboration & contribution!

### :heavy_check_mark: QA Passed

**Preconditions:**
- Install fresh Magento **`2.4-develop`** and **`PHP 8.1`**

**Manual testing scenario:**

As per the Description.


**Before:** :heavy_multiplication_x:

Screenshot 2023-11-30 at 10 31 46 AM


Screenshot 2023-11-30 at 10 32 49 AM


**After:** :heavy_check_mark:  

The one which we have shipped previously it is not appearing for second shipment.

Screenshot 2023-11-30 at 12 13 49 PM



Screenshot 2023-11-30 at 12 14 06 PM

**Pull request merged**
