### PR TITLE
MC-38185: [Magento Cloud] Issue with the new In store pickup when we …

### PR DESCRIPTION
**Pull request by tsviklinskyi**
…have multiple languages.

### Description (*)
ISSUE:
Issue with the new In store pickup when we have multiple languages.

STEPS TO REPRODUCE:

Install clean 2.4-develop + Inventory 1.2-develop
Create a new Source with Pickup enabled. The address has to be in Canada - Region: Quebec (create stock2 and assign this source to it)
Import data for SSA
php73 bin/magento inventory-geonames:import ca
Enable In Stock Pick up as shipping method
Set French (France) as the language of the store in Store > Config > General > Locale Options > Locale
At this point, in the steps from the merchant they said they installed a language pack. To simplify the steps to reproduce the issue, we can just execute the following query to have "Quebec" translated in french:
//get the region_id of Quebec
select * from directory_country_region_name where name like '%Quebec%';

//insert the translation
INSERT INTO directory_country_region_name SET locale = 'fr_FR', region_id = 76, name = 'Québec';
Add a product to cart and checkout (set Canada>Quebec as shipping and billing addresses)
Choose the pickup in store for the Quebec store (click on Loop button to display it in the pickup locations list)
Try to place an order
ACTUAL RESULT:
An error "Pickup Location Address does not match Shipping Address for In-Store Pickup Quote."

EXPECTED RESULT:
The order is placed

ADDITIONAL NOTES:

The issue is reproducible in http://web2-73.sparta.corp.magento.com/dev/rrubino/ee24dev/my-new-product.html
As per Merchant:
This happens because in file vendor/magento/module-inventory-in-store-pickup-quote/Model/IsPickupLocationShippingAddress.php line 71 there is a check of every fields in the quote_address.
In this case the Region stored in table inventory_source is "Quebec" but the region in the quote_address is "Québec" with an accent on the first e so the value does not match.
For the above issue Merchant has created the patch which is attached

### Fixed Issues (if relevant)

1. Fixes magento/inventory#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by zakdma** [comment]
@magento import pull request to https://github.com/magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@zakdma the pull request successfully imported.

**Comment by zakdma** [comment]
@magento import pull request to https://github.com/magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by zakdma** [comment]
@magento import pull request to https://github.com/magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@zakdma, an error occurred during the Pull Request import.

**Comment by tsviklinskyi** [comment]
@magento import pull request to https://github.com/magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@tsviklinskyi, an error occurred during the Pull Request import.

**Comment by tsviklinskyi** [comment]
@magento import pull request to https://github.com/magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@tsviklinskyi, an error occurred during the Pull Request import.

**Pull request merged**
