### PR TITLE
[TSG][2.3.6] MC-34987: MFTF tests causing high load on Jenkins agents in MTSv1 platform

### PR DESCRIPTION
**Pull request by zakdma**
### Bug - P1
* [MC-34987](https://jira.corp.magento.com/browse/MC-34987) [2.3] MFTF tests causing high load on Jenkins agents in MTSv1 platform

### Bamboo CI builds

- Not required for MFTF tests delivery

### Related Pull Requests

- CE https://github.com/magento/magento2ce/pull/5785
- EE https://github.com/magento/magento2ee/pull/2425
- B2B https://github.com/magento/magento2b2b/pull/1080

### CE Checklist

- [ ] PR is green on M2 Quality Portal
- [ ] Jira issues have accurate summary, meaningful description and have links to relevant documentation at the story/task level
- [ ] Semantic Version build failure is approved by architect (if build is red) <Architect Name>
- [ ] Pull Request approved by architect <Architect Name>
- [ ] Pull Request quality review performed by <name>
- [ ] All unstable functional acceptance tests are isolated (if any)
- [ ] All linked Zephyr tests are approved by PO and have Ready to Use status
- [ ] Travis CI build is green (for mainline CE only)
- [ ] Jenkins Unit, Extended FAT CE, Extended FAT EE and Extended FAT B2B builds are green

Created by : @zakdma
Internal PR: https://github.com/magento-tsg/magento2ce/pull/826

### CODE REVIEW

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run Integration Tests

**Comment by zakdma** [comment]
@magento run Functional Tests CE,Functional Tests CE

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by zakdma** [comment]
@magento run Functional Tests CE

**Comment by bubasuma** [comment]
@magento run Functional Tests CE

**Comment by bubasuma** [comment]
@magento run Functional Tests B2B, Functional Tests EE, Integration Tests

**Comment by bubasuma** [comment]
This fix is vital for 2.3-develop delivery.

**Review by sidolov — APPROVED** [review]

**Pull request merged**
