### PR TITLE
2366: Remove excess fixtures from In-Store Pickup module

### PR DESCRIPTION
**Pull request by yuriichayka**
Removed excessive fixture with some adjustments

### Description (*)
Removed excessive '_app/code/Magento/InventoryInStorePickup/Test/_files/mark_sources_as_pickup_location.php_' fixture, and changed a test for successful passing 

### Fixed Issues (if relevant)

1. magento/magento2#2366:Remove excess fixtures from In-Store Pickup module

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2474) <br/>All committers have signed the CLA.

**Comment by ishakhsuvarov** [comment]
@magento run Static Tests build

**Comment by swnsma** [comment]
@magento run Static Tests build

**Comment by swnsma** [comment]
@magento run Static Tests build

**Review by swnsma — APPROVED** [review]

**Comment by ishakhsuvarov** [comment]
@yuriichayka @swnsma I've checked logs in internal CI and static test failure is not related to the content of the PR. While problem is getting fixed I'll merge it overriding the check.

**Pull request merged**
