### PR TITLE
Sync with mainline 2.3-develop

### PR DESCRIPTION
**Pull request by ishakhsuvarov**
## Description
This PR is a routine sync of 2.3-develop from magento/magento2 and magento/inventory repo. Current 2.3-develop is affected by MFTF issue preventing test execution.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2495) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2495) before we can accept your contribution.<br/>**4** out of **13** committers have signed the CLA.<br/><br/>:white_check_mark: arhiopterecs<br/>:white_check_mark: naydav<br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: larsroettig<br/>:x: magento-engcom-team<br/>:x: vzabaznov<br/>:x: BaDos<br/>:x: joanhe<br/>:x: edenduong<br/>:x: arushibansal013<br/>:x: wpalmer<br/>:x: rganin<br/>:x: MilaLesechko

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests build

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests build

**Comment by ishakhsuvarov** [comment]
SVC and Static build failures are not related to Inventory code and are caused by mainline changes.

**Pull request merged**
