### PR TITLE
MC-18332 MySQL search engine removal

### PR DESCRIPTION
**Pull request by cpartica**
Mysql search index Removal MSI plugins issue

### Description (*)
Plugins are existing on removed classes that are part of mysql search index in MSI

### Fixed Issues (if relevant)
https://jira.corp.magento.com/browse/MC-18332

EXPECTED RESULT
MSI should work without mysql search index plugins

ACTUAL RESULT
MSI doesn't work without mysql search index plugins when those classes that are plugged in are removed

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento run all tests

**Comment by cpartica** [comment]
@magento run all tests

**Comment by cpartica** [comment]
@magento run all tests

**Comment by cpartica** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by cpartica** [comment]
@magento run Functional Tests B2B

**Comment by cpartica** [comment]
@magento run Functional Tests B2B

**Comment by cpartica** [comment]
@magento run Functional Tests B2B

**Comment by cpartica** [comment]
@magento run all tests

**Comment by cpartica** [comment]
B2b failing because of unstable tests marked in MC-34516

**Comment by cpartica** [comment]
This PR must be merged before https://github.com/magento/magento2ce/pull/5688

**Comment by cpartica** [comment]
@magento run all tests

**Comment by sidolov** [comment]
Failed unstable tests listed in https://jira.corp.magento.com/browse/MC-34516

**Pull request merged**
