### PR TITLE
Patch performance legacy stock view

### PR DESCRIPTION
**Pull request by wexo-team**
### Description
Legacy stock status view is slowing frontend and product save. It slows down because there are no indexes on the view (and should not be possible to have), we only see this issue with the default stock source as thats the only 1 which gets created as a view. 

We experienced this issue on a shop with 70k products, and got a result that was 10x faster with a table that has indexes.

### Manual testing scenarios
1. Magento 2.3.0
2. Multi Source Inventory enabled, and applied patch so that inventory_stock_1 view is created
3. Over 1k products on shop and conncted to website
4. Save products and see that it keeps querying inventory_stock_1
5. Go to frontend and see that it takes long(er) time to load, as there are no indexes on the view

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2025) <br/>All committers have signed the CLA.

**Comment by maghamed** [comment]
Hey @wexo-team , 

that's an interesting idea to use Triggers instead of View to bump the performance on reading operations, especially Catalog and Search result pages.

But even View is a temporary solution until we would have Bundle product supported. Also in Magento we used to separate Data tier out of Business Logic, that's why we tend not to use triggers and stored procedures on DB level. 

As I see you've applied the fix for your Magento website and that gave you 10x boost for Default stock. Do you want to share that on Magento MSI weekly meeting on Friday? 

Btw, What MSI version do you use 1.0.3 or 1.1.0? As in 1.1.0 we've addressed most of the performance issue on the front-end (catalog, search result, shopping cart).
The issue which we are still experiencing is Product Save but in this case, the root cause is not MySQL View, but data synchronization happening between Legacy Inventory and New Inventory (via plugins).

@phoenix128 recently finished working on the corresponding PR - https://github.com/magento-engcom/msi/pull/2056 and we would be ready to merge it soon.

Thus, if you have time to experiment it would be great to compare the performance of your store with Trigger and Without trigger on MSI 1.1.0 on next environments:
- Magento 2.3.0 + Magento MSI 1.1.0 + your fix (MySQL Trigger instead of View)
vs
- Magento 2.3.0 + Magento MSI 1.1.0 + Riccardo's PR

Do you have time to help us with this investigation @wexo-team ?

**Comment by wexo-team** [comment]
Hi @maghamed 

Thanks for taking a look at the merge request. It's valuable feedback, and I understand your concerns regarding implementing a "data synchronization" at DB-level as it creates an even stronger dependency on MySQL, although this solution is robust in terms of securing up-to-date data - just like the view. The issue we experienced was that for each product rendered on the category page, a ~2s query was fired to get salable status as we have a relatively large amount of products and thus stock items. With a `EXPLAIN SELECT` we found out, we didn't hit indexes on the view.

When we implemented the fix, we used 1.0.3, but have since updated. We would love to give results about performance with the two combinations and to see if it has been improved dramatically.

Regarding the MSI weekly meeting: can you tell us about the time and timezone for the meeting? We would be honored to attend. I know it's today, so depending on when it is, would it make sense to attend next friday instead?

Again, thanks for the feedback. Wish you a good day.

**Comment by maghamed** [comment]
@wexo-team 

The meeting will start in 40 minutes. 5 P.M. CET 
Reachable by this link - https://bluejeans.com/2326679047/9005?src=calendarLink


Also, we got new PR recently which should improve the Product Save performance 
https://github.com/magento-engcom/msi/pull/2085
gonna be merged quite soon into the mainline

**Comment by wexo-team** [comment]
Hi @maghamed 

We will conduct tests (hopefully) today and/or tomorrow. Would it make sense if we attend to the weekly meeting tomorrow?

**Comment by ishakhsuvarov** [comment]
@wexo-team It definitely would make sense. Please don't hesitate to join

**Comment by maghamed** [comment]
Hey @wexo-team , do you have some spare time for performance comparison? We have delivered some performance improvements into MSI mainline, which suppose to address the issue mentioned by you. Could you please make a performance comparison with your PR once again ?

**Comment by ishakhsuvarov** [comment]
Hi @wexo-team 

Thank you once more for this PR as this solution is very interesting and we have been keeping it on the radar for a long time now. 

Unfortunately, for now we have chosen to go the way of not using mysql view where possible and it seems to show similar results performance-wise. After all, this view is not a complete solution and expected to be materialized into a normal stock table down the road.

Thanks a lot for developing, sharing, measuring and presenting this!

**Pull request closed without merging**
