### PR TITLE
Fix functional test to work with additional product grid fields.

### PR DESCRIPTION
**Pull request by nmalevanec**
### Description
Fix AdminUserSetStatusForEachSourceItemTest to pass with additional product grid field "Special Price", which has been added in https://github.com/magento/magento2/pull/20474
### Fixed Issues (if relevant)
1. None.
### Manual testing scenarios
1. None.

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
✅ Tested Functional Test suite with this branch. Internal Jenkins link for reference: [click](https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/15174/).
✅ Travis CI build job may be skipped for this PR. It does not cover changes in any way.

**Review by ishakhsuvarov — APPROVED** [review]

**Comment by orlangur** [comment]
@nmalevanec @ishakhsuvarov actually, additional column must not be added in the first place. Please revert.

**Comment by nmalevanec** [comment]
> @nmalevanec @ishakhsuvarov actually, additional column must not be added in the first place. Please revert.

@orlangur, test initially worked incorrectly, this changes is correct, even if there are not additional columns. There is not "quantity" column in multistock mode.

**Comment by orlangur** [comment]
@nmalevanec ok then, I didn't check this PR deeply. Thanks for the quick response!

**Pull request merged**
