### PR TITLE
Sync with core 2.3-develop

### PR DESCRIPTION
**Pull request by ishakhsuvarov**
### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2422) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2422) before we can accept your contribution.<br/>**2** out of **18** committers have signed the CLA.<br/><br/>:white_check_mark: Stepa4man<br/>:white_check_mark: naydav<br/>:x: magento-engcom-team<br/>:x: michaelyu0123<br/>:x: RyanZolper<br/>:x: dyushkin<br/>:x: hostep<br/>:x: magento-cicd2<br/>:x: dthampy<br/>:x: joanhe<br/>:x: viktym<br/>:x: SeruyV<br/>:x: nikita-shcherbatykh<br/>:x: gwharton<br/>:x: OlgaVasyltsun<br/>:x: engcom-Foxtrot<br/>:x: VeronikaYarats<br/>:x: sivaschenko<hr/>**OlgaVasyltsun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by nmalevanec** [comment]
@ishakhsuvarov, there is problem with order placement from admin occurred on this PR
### Steps to reproduce:
1. Create additional website with store and store view.
2. Create additional stock with source, assigned to created additional website.
3. Create simple product with created source and assigned to created website. (Make sure, product not assigned to default source).
4. Start creating new order from admin area on additional website.
5. Add created product to order with qty 1.

### Expected result
1. Product added successfully

### Actual result
1. Product is not available error occurs.


This is the reason AdminUserCreateOrderFromTestWebsiteWithSimpleProductWithInventoryOnDefaultAndTestStockTest fails.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2422) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2422) before we can accept your contribution.<br/>**2** out of **18** committers have signed the CLA.<br/><br/>:white_check_mark: Stepa4man<br/>:white_check_mark: naydav<br/>:x: magento-engcom-team<br/>:x: michaelyu0123<br/>:x: RyanZolper<br/>:x: dyushkin<br/>:x: hostep<br/>:x: magento-cicd2<br/>:x: dthampy<br/>:x: joanhe<br/>:x: viktym<br/>:x: SeruyV<br/>:x: nikita-shcherbatykh<br/>:x: gwharton<br/>:x: OlgaVasyltsun<br/>:x: engcom-Foxtrot<br/>:x: VeronikaYarats<br/>:x: sivaschenko<hr/>**OlgaVasyltsun** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2422) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2422) before we can accept your contribution.<br/>**3** out of **14** committers have signed the CLA.<br/><br/>:white_check_mark: naydav<br/>:white_check_mark: tomreece<br/>:white_check_mark: VeronikaYarats<br/>:x: gwharton<br/>:x: Roman Lytvynenko<br/>:x: magento-engcom-team<br/>:x: viktym<br/>:x: joanhe<br/>:x: magento-cicd2<br/>:x: irenelagno<br/>:x: edenduong<br/>:x: soumyau<br/>:x: zakdma<br/>:x: engcom-Foxtrot<hr/>**Roman Lytvynenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2422) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2422) before we can accept your contribution.<br/>**4** out of **13** committers have signed the CLA.<br/><br/>:white_check_mark: tomreece<br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: Stepa4man<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: joanhe<br/>:x: magento-cicd2<br/>:x: krissyhiserote<br/>:x: AlexMaxHorkun<br/>:x: edenduong<br/>:x: magento-engcom-team<br/>:x: serhii-balko<br/>:x: rostyslav-hymon<br/>:x: sivaschenko

**Comment by ishakhsuvarov** [comment]
Failure for SVC and Static test builds are originating from changes in the core. Unrelated to Inventory.

**Pull request merged**
