### PR TITLE
WIP: FIX #27117 Invalid functional Test names

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
Fix the Test names, rename wrong files.
As a side effect, more tests can be run than previously.

### Similar Pull Requests
* https://github.com/magento/magento2/pull/27118
* https://github.com/magento/partners-magento2b2b/pull/54
* https://github.com/magento/partners-magento2ee/pull/151
* https://github.com/magento/magento2-page-builder/pull/399

### To be done later
* https://github.com/magento/inventory/pull/2857

### Fixed Issues (if relevant)
1. magento/magento2#27117

### Manual testing scenarios (*)
N/A

### Questions or comments
This change might cause hundreds of failures as previously ignored will be run now.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by lbajsarowicz** [comment]
Tests are not being generated as `magento/inventory` had tests that were previously ignored by the runner. Renaming them to correct pattern caused running them on CI. As a result - tests that were not run - are not causing the issues with `stepKey` references.

**Review by sidolov — DISMISSED** [review]

**Comment by sidolov** [comment]
Hi @lbajsarowicz , are you going to fix the rest of the issues?

**Comment by lbajsarowicz** [comment]
@sidolov There's so much wrong in MSI when it comes to MSI, that it's my lowest priority.
If you find someone **who knows MSI** and can fix the tests that are ignored for months, I'd love to pass by that PR to be continued by other(s).

**Review by sidolov — APPROVED** [review]

**Comment by lbajsarowicz** [comment]
@sidolov :clinking_glasses: Thanks! That's awesome you've handled that.

**Pull request merged**
