### PR TITLE
Merge with the latest 2.3-develop from Magento

### PR DESCRIPTION
**Pull request by ishakhsuvarov**
### Description
Another routine sync

### Expected updates
* MFTF Action Groups required for multiple PRs on hold
* Updated MFTF version

### Checklist
* [ ] Verify number of executed mftf tests even if run is green
* [x] Verify logs for all of the tests expected to fail (SVC, Static)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2591) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2591) before we can accept your contribution.<br/>**4** out of **15** committers have signed the CLA.<br/><br/>:white_check_mark: o-iegorov<br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: VitaliyBoyko<br/>:white_check_mark: p-bystritsky<br/>:x: magento-cicd2<br/>:x: dhorytskyi<br/>:x: cpartica<br/>:x: dthampy<br/>:x: prabhuram93<br/>:x: serhii-balko<br/>:x: zakdma<br/>:x: edenduong<br/>:x: OleksandrBurianyk<br/>:x: brunoroeder<br/>:x: kkorushkin<hr/>**kkorushkin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by ishakhsuvarov** [comment]
Attempting to add content of MFTF PRs to see if there are any new failures.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2591) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2591) before we can accept your contribution.<br/>**4** out of **18** committers have signed the CLA.<br/><br/>:white_check_mark: VitaliyBoyko<br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: p-bystritsky<br/>:white_check_mark: okolesnyk<br/>:x: serhii-balko<br/>:x: zakdma<br/>:x: edenduong<br/>:x: OleksandrBurianyk<br/>:x: brunoroeder<br/>:x: kkorushkin<br/>:x: prabhuram93<br/>:x: dthampy<br/>:x: magento-cicd2<br/>:x: omiroshnichenko<br/>:x: magento-engcom-team<br/>:x: cpartica<br/>:x: dhorytskyi<br/>:x: bubasuma<hr/>**kkorushkin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2591) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2591) before we can accept your contribution.<br/>**4** out of **19** committers have signed the CLA.<br/><br/>:white_check_mark: VitaliyBoyko<br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: p-bystritsky<br/>:white_check_mark: okolesnyk<br/>:x: serhii-balko<br/>:x: zakdma<br/>:x: edenduong<br/>:x: OleksandrBurianyk<br/>:x: brunoroeder<br/>:x: kkorushkin<br/>:x: prabhuram93<br/>:x: dthampy<br/>:x: magento-cicd2<br/>:x: omiroshnichenko<br/>:x: magento-engcom-team<br/>:x: cpartica<br/>:x: dhorytskyi<br/>:x: bubasuma<br/>:x: thiaramus<hr/>**kkorushkin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests build

**Pull request merged**
