### PR TITLE
[WIP]MFTF tests stabilization.

### PR DESCRIPTION
**Pull request by nmalevanec**
### Fixed Issues (if relevant)

1. https://github.com/magento/inventory/issues/3007: Fix flaky AdminCreateShipmentWithDeletedSimpleProductCustomStockTest 
2. https://github.com/magento/inventory/issues/2995: Fix flaky AdminManageStockOnProductPageTurnedOffForSimpleProductTest
3. https://github.com/magento/inventory/issues/2998: Fix flaky AdminMassActionUnAssignAllProductSourcesFromSimpleProductTest
4. https://github.com/magento/inventory/issues/3008: Fix flaky AdminCreateCreditMemoSimpleProductWithChangedSkuDefaultStockTest
### Manual testing scenarios (*)

1. none.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nmalevanec** [comment]
@magento run all tests

**Comment by nmalevanec** [comment]
@magento run all tests

**Comment by nmalevanec** [comment]
@magento run all tests

**Comment by nmalevanec** [comment]
@magento run all tests

**Comment by nmalevanec** [comment]
@magento run all tests

**Comment by nmalevanec** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by nmalevanec** [comment]
@magento run all tests

**Pull request merged**
