### PR TITLE
Store Pickup automated tests stabilization

### PR DESCRIPTION
**Pull request by ishakhsuvarov**
### Description (*)
This Pull Request is intended to be used as a container for `Store Pickup` automated tests stabilization.

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: ysapiga<br/>:x: magento-engcom-team<br/>:x: zakdma<br/>:x: VeronikaYarats<br/>:x: soumyau

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: magento-engcom-team<br/>:x: zakdma<br/>:x: VeronikaYarats<br/>:x: soumyau

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: magento-engcom-team<br/>:x: zakdma<br/>:x: VeronikaYarats<br/>:x: soumyau

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: magento-engcom-team<br/>:x: zakdma<br/>:x: VeronikaYarats<br/>:x: soumyau

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: zakdma<br/>:x: VeronikaYarats<br/>:x: magento-engcom-team<br/>:x: soumyau

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: VeronikaYarats<br/>:x: magento-engcom-team<br/>:x: soumyau

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **9** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: VeronikaYarats<br/>:x: magento-engcom-team<br/>:x: soumyau

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: VeronikaYarats<br/>:x: magento-engcom-team<br/>:x: soumyau<br/>:x: hostep

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: VeronikaYarats<br/>:x: magento-engcom-team<br/>:x: soumyau<br/>:x: hostep

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: magento-engcom-team<br/>:x: zakdma<br/>:x: VeronikaYarats<br/>:x: soumyau

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**6** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: nmalevanec<br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: magento-engcom-team<br/>:x: zakdma<br/>:x: VeronikaYarats<br/>:x: soumyau

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests build

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2392) before we can accept your contribution.<br/>**5** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: VladimirZaets<br/>:white_check_mark: naydav<br/>:white_check_mark: larsroettig<br/>:white_check_mark: ishakhsuvarov<br/>:white_check_mark: mastiuhin-olexandr<br/>:x: soumyau<br/>:x: hostep

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
SVC failure is fine, as store pickup is expected to be a minor release.

**Pull request merged**
