### PR TITLE
Marked Inventory interfaces and blocks as API

### PR DESCRIPTION
**Pull request by ProkopovVitaliy**
### Fixed Issues (if relevant)

1. Fixes magento/magento2#32067

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ProkopovVitaliy** [comment]
@magento run all tests

**Review by coderimus — APPROVED** [review]

**Comment by sidolov** [comment]
@ProkopovVitaliy could you please additionally mark classes as described in https://github.com/magento/magento2/issues/32067: 
Magento\InventoryShippingAdminUi\Block\Adminhtml\Shipment\Inventory
Magento\InventoryShippingAdminUi\Block\Adminhtml\Order\View\ShipButton
Thanks!

**Comment by ProkopovVitaliy** [comment]
> @ProkopovVitaliy could you please additionally mark classes as described in [magento/magento2#32067](https://github.com/magento/magento2/issues/32067):
> Magento\InventoryShippingAdminUi\Block\Adminhtml\Shipment\Inventory
> Magento\InventoryShippingAdminUi\Block\Adminhtml\Order\View\ShipButton
> Thanks!

@sidolov requested classes already marked:
[Magento\InventoryShippingAdminUi\Block\Adminhtml\Shipment\Inventory](https://github.com/magento/inventory/blob/1.2-develop/InventoryShippingAdminUi/Block/Adminhtml/Shipment/Inventory.php#L19)
[Magento\InventoryShippingAdminUi\Block\Adminhtml\Order\View\ShipButton](https://github.com/magento/inventory/blob/1.2-develop/InventoryShippingAdminUi/Block/Adminhtml/Order/View/ShipButton.php#L20)

**Comment by coderimus** [comment]
@stansm please, check Vitali's comment. Looks like they already marked. Thank you :)

**Review by coderimus — APPROVED** [review]

**Comment by ProkopovVitaliy** [comment]
@magento run Functional Tests B2B

**Comment by ProkopovVitaliy** [comment]
@magento run Database Compare

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@sidolov the pull request successfully imported.

**Comment by gabrieldagama** [comment]
@magento import pr to https://github.com/magento-commerce/magento2ce

**Comment by gabrieldagama** [comment]
@magento import pr to https://github.com/magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@gabrieldagama, an error occurred during the Pull Request import.

**Comment by magento-engcom-team** [comment]
@gabrieldagama the pull request successfully imported.

**Pull request merged**
