### PR TITLE
Fix issue #1543 Low Stock Report

### PR DESCRIPTION
**Pull request by aleron75**
This PR aims at fixing the low stock report not displaying any data in single source mode.

See issue #1543 

### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by TomashKhamlai** [comment]
QA Passed
fixed

**Comment by aleron75** [comment]
Open points:
- mass stock update doesn't populate the table
- have to check import where I guess we could have the same issue

**Comment by aleron75** [comment]
After a call with @smoskaluk we decided to remove the WIP label and proceed with merging of current PR. If further issues arise on the low stock report topic we will open them.

**Comment by maghamed** [comment]
latest build 
https://m2build.devops.magento.com/job/Existing-PR-Tests/8560/
with PR https://github.com/magento/magento2ce/pull/3324

Magento 2.3-develop
https://m2build.devops.magento.com/job/Existing-PR-Tests/8561/
https://github.com/magento/magento2ce/pull/3323

**Review by maghamed — APPROVED** [review]

**Pull request merged**
