### PR TITLE
MSI-2281: Add Sources column to the Sales Order Grid in Magento Admin panel

### PR DESCRIPTION
**Pull request by seruymt**
### Description (*)
Display allocated sources per order in order grid

### Fixed Issues (if relevant)

1. magento/inventory#2281: Add Sources column to the Sales Order Grid in Magento Admin panel

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by smoskaluk** [comment]
Hi @seruymt ! When I do partial shipment for order - new line in "Allocated sources" adding, even for default source. Please recheck 
image

**Comment by ishakhsuvarov** [comment]
@seruymt Any chance you would be able to take a look at the quality report?

Thanks!

**Comment by seruymt** [comment]
@ishakhsuvarov I'll fix it

**Comment by sidolov** [comment]
Hi @seruymt any chance to fix reported issue? It seems to be a minor fix. Thanks!

**Comment by sidolov** [comment]
@magento run Unit Tests

**Review by sidolov — APPROVED** [review]

**Pull request merged**
