### PR TITLE
Added resource to filter product collection by source code

### PR DESCRIPTION
**Pull request by TadeuRodrigues**
### Description (*)
I create a resource to filter products from collection by source code.

### Fixed Issues (if relevant)
1. magento/inventory#2424: Adding source filter to product collection will be helpful

### Manual testing scenarios (*)
1. Load product Collection
2. execute addSourceCodeFilterToCollection->execute() with product collection and source code

### Contribution checklist (*)
 - [X] Pull request has a meaningful description of its purpose
 - [X] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — CHANGES_REQUESTED** [review]
Hi @TadeuRodrigues , I'm not sure that we should keep unused classes in the code base, since this code may never be used by anybody. If you are using such logic in the 3d party extension, this class, probably, should be a part of the extension.

**Comment by TadeuRodrigues** [comment]
@sidolov I'm proposing this code to resolve that issue #2424 , can u check again?

**Comment by Stepa4man** [comment]
@ishakhsuvarov Is this really a feature?
I agree with @sidolov, until we don't use it in the core - we don't need it. If you see some usages of this filter in core and want to avoid code duplication with this service - you are welcome. But if it's just unused class in the core...

**Review by Stepa4man — CHANGES_REQUESTED** [review]
@ishakhsuvarov Is this really a feature?
I agree with @sidolov, until we don't use it in the core - we don't need it. If you see some usages of this filter in core and want to avoid code duplication with this service - you are welcome. But if it's just unused class in the core...

**Comment by sidolov** [comment]
Hi @TadeuRodrigues  , due to changes in the repository structure (Magento core code is extracted from the MSI code base) we have changed the base branch to `1.1-develop-legacy`. We will keep this branch for a while to make a smooth transition, in the meanwhile, please, apply changes from the current PR to the new code base structure in `1.1-develop` branch. 

[Installation Guide](https://github.com/magento/inventory/wiki/Metapackage-Installation-Guide) may be helpful for local project development. 

Let me know if you need help or have questions!
Thank you for your collaboration!

**Comment by sidolov** [comment]
Hi @TadeuRodrigues , I'm closing the PR since it's targeting the legacy branch and cannot be processed. Feel free to work on the implementation and to reopen it to the `1.2-develop` branch with the new structure. Thank you for collaboration!

**Pull request closed without merging**
