### PR TITLE
MC-38194: [Question - Cloud] Inventory Inconsistency Questions

### PR DESCRIPTION
**Pull request by serhii-balko**
fixes the issue
https://jira.corp.magento.com/browse/MC-38194

### CODE REVIEW

**Comment by serhii-balko** [comment]
@magento run all tests

**Comment by serhii-balko** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento import pr to magento-commerce/inventory

**Comment by magento-engcom-team** [comment]
@sidolov the pull request successfully imported.

**Pull request merged**
