### PR TITLE
HOTFIX: #26607 Fix failing CI due to Functional Tests

### PR DESCRIPTION
**Pull request by lbajsarowicz**
### Description (*)
During fix of magento/magento2#26607 with magento/magento2#26608 - I've noticed that the test is extended and actually - the Admin session is killed, completely ignoring the fact, that further actions that are performed in original tests still need the session.

* Reorganized tests and it's extensions to work properly.
* Removed the `cache:flush` bad practice loved by Core Team <3
* Fixed issues caused by missing indexing (adding `cron:run --group=index`)
* Invalid search returns returned (duplicated products)
* Extended Credit Card expiration period to another 4 years

All above mentioned also for B2B and EE version.

### Related Pull Requests
* https://github.com/magento/magento2/pull/26608
* https://github.com/magento/partners-magento2ee/pull/135
* https://github.com/magento/partners-magento2b2b/pull/45
* https://github.com/magento/inventory/pull/2820

### Fixed Issues (if relevant)
1. https://github.com/magento/magento2/issues/26607

### Manual testing scenarios (*)
1. Change README.md for any module
2. Submit PR to Github

### Questions or comments
:man_facepalming: 

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

Original Pull Request: https://github.com/magento/inventory/pull/2820

### CODE REVIEW

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Review by lbajsarowicz — COMMENTED** [review]
That looks new to me :-)

**Review by sidolov — APPROVED** [review]

**Pull request merged**
