### PR TITLE
MC-35060: Credit memos with downloadable product and numeric SKU fail to process and return white screen

### PR DESCRIPTION
**Pull request by victor-v-rad**
### Bug
* [MC-35060](https://jira.corp.magento.com/browse/MC-35060) Credit memos with downloadable product and numeric SKU fail to process and return white screen

### Related Pull Requests
none

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by victor-v-rad** [comment]
@magento run Static Tests

**Comment by victor-v-rad** [comment]
@magento run Static Tests

**Comment by victor-v-rad** [comment]
@magento run all tests

**Comment by victor-v-rad** [comment]
Unit test was created instead of integration to avoid creation dependency InventorySales module on Downloadable module. Unit test covers scenario from the issue

**Comment by victor-v-rad** [comment]
@sidolov please review
Unit test was created instead of integration to avoid creation dependency InventorySales module on Downloadable module. Unit test covers scenario from the issue

**Comment by victor-v-rad** [comment]
@mbrinton01 please approve the PR for 1.1-develop branch. The PR https://github.com/magento/inventory/pull/3135 for 1.2-develop was created as well

**Review by mbrinton01 — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Pull request merged**
