### PR TITLE
MSI-878: Notify Quantity applied to Product in Advanced Inventory on Product page in Admin doesn\t work

### PR DESCRIPTION
**Pull request by seruymt**
https://github.com/magento-engcom/msi/issues/878

### CODE REVIEW

**Comment by maghamed** [comment]
2.3.0-release - https://m2build.devops.magento.com/job/Existing-PR-Tests/8652/

2.3-develop - https://m2build.devops.magento.com/job/Existing-PR-Tests/8654/

use request - https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/7365/

**Comment by maghamed** [comment]
2.3.0 - https://m2build.devops.magento.com/job/Existing-PR-Tests/8702/

2.3-develop - https://m2build.devops.magento.com/job/Existing-PR-Tests/8703/

user request - https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/7433/

**Comment by smoskaluk** [comment]
@seruymt Please look into failed functional test: http://10.234.230.152:8080/job/Functional-Tests-B2B/458
1.Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.StorefrontSimpleProductAssignedToNonDefaultSourceCreatedByAdminUserTest - Link or Button or CSS or XPath element with '.admin__data-grid-header[data-bind='afterRender: $data.setToolbarNode'] button[data-action='grid-filter-expand']' was not found. 
image

**Comment by maghamed** [comment]
2.3.0 - https://m2build.devops.magento.com/job/Existing-PR-Tests/8714/
2.3-develop - https://m2build.devops.magento.com/job/Existing-PR-Tests/8715/

user request - https://m2build-ur.devops.magento.com/job/All-User-Requested-Tests/7461/

**Comment by maghamed** [comment]
2.3.0 https://m2build.devops.magento.com/job/Existing-PR-Tests/8716/

**Pull request merged**
