### PR TITLE
#3062 Added reservation quantity check to frontend

### LINKED ISSUE #3060: Product having zero salable quantity results in stock in product list page and out of stock in view page.
Preconditions (*)

    1. Magento 2.3.5-p1(MSI enabled)

Steps to reproduce (*)

    1. Create a simple product with qty = 1
    2. Place an order that will cause the product to have 0 salable quantity
    3. The Salable Quantity drops to zero, while the Quantity remains at 1.

Expected result (*)

    1. The product, having Salable Quantity 0, should display out of stock label in both product list page and product view page.

Actual result (*)

    1. The product remains in stock in product list page and out of stock in view page.

P.S. If you open the product page then it does show correctly as out of stock product.

admin panel stock

スクリーンショット 2020-05-28 10 32 17

product list page

スクリーンショット 2020-05-28 13 51 25

product view page

スクリーンショット 2020-05-28 13 55 54

Does anyone facing same? Please help me on this thanks!

### LINKED ISSUE #3062: Product having zero salable quantity results in stock in product list page and out of stock in view page.
Preconditions (*)

 1. Magento 2.3.5-p1(MSI enabled)

Steps to reproduce (*)

1. Create a simple product with qty = 1
2. Place an order that will cause the product to have 0 salable quantity
3. The Salable Quantity drops to zero, while the Quantity remains at 1.

Expected result (*)

1. The product, having Salable Quantity 0, should display out of stock label in both product list page and product view page.

Actual result (*)

1. The product remains in stock in product list page and out of stock in view page.

P.S. If you open the product page then it does show correctly as out of stock product.

admin panel stock
スクリーンショット 2020-05-22 12 18 16

product list page
スクリーンショット 2020-05-22 12 11 27
product view page

スクリーンショット 2020-05-22 12 12 09

### LINKED ISSUE #31117: Product show in stock even if the salable quantity is 0
### Preconditions (*)

1. Magento Open Source 2.4.1 with sample data
2.

### Steps to reproduce (*)

1. Make an order of a product and buy everything (example if 5 in stock, buy all 5)
2. Go to your admin and this product QTY should be 5 and Salable QTY should be 0. Which is normal since the order has not been shipped yet. 

### Expected result (*)

1. Front end should show "Out of stock"
2. We should NOT have the "add to cart" Button

### Actual result (*)

1. Front end shows "in stock".
2. Add to cart button is available
3. When we try to cart, we get a message "The requested qty is not available"

NOTE:
See the related issues:
- https://github.com/magento/magento2/issues/31267
- MSI Repo https://github.com/magento/inventory/issues/3102
- https://github.com/magento/inventory/issues/3062
- https://github.com/magento/magento2/issues/25877
- MSI repo https://github.com/magento/inventory/issues/2708
- https://github.com/magento/magento2/issues/27223
---
Please provide [Severity](https://devdocs.magento.com/guides/v2.3/contributor-guide/contributing.html#backlog) assessment for the Issue as Reporter. This information will help during Confirmation and Issue triage processes.

- [ ] Severity: **S0** _- Affects critical data or functionality and leaves users without workaround._
- [ ] Severity: **S1** _- Affects critical data or functionality and forces users to employ a workaround._
- [x ] Severity: **S2** _- Affects non-critical data or functionality and forces users to employ a workaround._
- [ ] Severity: **S3** _- Affects non-critical data or functionality and does not force users to employ a workaround._
- [ ] Severity: **S4** _- Affects aesthetics, professional look and feel, “quality” or “usability”._

### PR DESCRIPTION
**Pull request by greezlu**
### Description (*)

Adding product reservation quantity check to the frontend. To prevent situations where product is in "In Stock" status but you can't add it to a cart.

### Fixed Issues (if relevant)

1. Fixes magento/inventory#3062
2. Fixes magento/inventory#3060
3. Fixes magento/magento2#31117

### Manual testing scenarios (*)

1. Create a new product.
4. Create url key for product access from frontend.
5. Set product stock quantity to 1.
6. Create a new order with this product **without shipping it**.
7. Go to the product view page on frontend.
8. The product should be in "Out of stock" status.

### Questions or comments

Without this additional check product will be in "In Stock" status but you will get an error trying to add such product to your cart.

Also, this check should avoid all other product types except **Simple**.

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Djohn12** [comment]
Hi,

Thanks for that contribution @greezlu 
Are you still making changes to your code ?

I tried applying your patch on my local env and it does seem to fix the issue on product page effectively but products are still marked as In stock on category pages even when salable is 0.

**Comment by greezlu** [comment]
Hi, @Djohn12 
Yeah, turns out it not that simple)
I'm still working on it. But I think I'm close.

Should I tag you after I finish?

**Comment by Djohn12** [comment]
I believe I can take some time today to assist you if I can help ?

Need to fix this issue for a client.

Do you have any trail to follow to make it work on category pages ? Any point you might need assistance to look into ?

**Comment by greezlu** [comment]
@Djohn12 
Actually yes, you can help.

I found different way to approach. There's select queries to load product(s) which needs to be modified. I've done it incorrectly, may be you can fix it. Main idea is the same: check reservations for simple products. But to do it on a db query stage. Here are patches, where you can find those queries. Good luck.

For collections:
`magento/module-inventory-catalog`
[github-issue-3062-1.patch.zip](https://github.com/magento/inventory/files/8707242/github-issue-3062-1.patch.zip)

For single product:
`magento/module-inventory-indexer`
[github-issue-3062-2.patch.zip](https://github.com/magento/inventory/files/8707243/github-issue-3062-2.patch.zip)

**Comment by Djohn12** [comment]
Thanks for all that information @greezlu !

Looking into your zip patches and the stack trace for Magento Catalog page I'm not sure updating the collection will do the trick though.

As far as I can tell, the only check to render the "add to cart" CTA on catalog pages depends on the call `$_product->isSaleable()` in `magento/module-catalog/view/frontend/templates/product/list.phtml`

That call goes through 
- `vendor/magento/module-catalog/Model/Product::isSalable()`
- that method internally calls `vendor/magento/module-catalog/Model/Product::isAvailable()`
- which ends calling `magento/module-catalog/Model/Product/Type/AbstractType::isSalable($product)`
- which is defined as following (as per Magento 2.4.3-p2) : 

```
 /**
 * Check is product available for sale
 *
 * @param \Magento\Catalog\Model\Product $product
 * @return bool
 */
public function isSalable($product)
{
    $salable = $product->getStatus() == \Magento\Catalog\Model\Product\Attribute\Source\Status::STATUS_ENABLED;
    if ($salable && $product->hasData('is_salable')) {
        $salable = $product->getData('is_salable');
    }

    return (bool)(int)$salable;
}
```

I don't see anything allowing for the template update after that call.

I'm thinking about modifying `magento/module-catalog/Model/Product/Type/AbstractType::isSalable($product)` to make it call `magento/module-inventory-indexer/Model/IsProductSalable::getIsSalable(string $sku, int $stockId)` you already fixed for product pages.

I reckon this could also be part of a Plugin/Observer call, not sure what would be the best implementation.

Would you consider it a viable solution ?

Let me know if what you think :)

**Comment by Djohn12** [comment]
To add more information : 

The `magento/module-checkout/Controller/Cart/Add.php` Action called on "add to cart" action does call `magento/module-inventory-indexer/Model/IsProductSalable::getIsSalable(string $sku, int $stockId)` to check for product salability.

I feel it'd be right to make that same check when displaying product availability on catalog pages and get consistent results

**Comment by greezlu** [comment]
> I'm not sure updating the collection will do the trick though.

Block of the `list.phtml` template  loads products collection. You see call `isSalable()` for each of them. So I think it will.

> Seems right to me to make that same check to display product availability on catalog pages as well.

It's not the same. You're trying to add only **one** product at a time to the cart. Your performance don't mind additional check. But doing it for each product in a list is quite expensive.

> I reckon this could also be part of a Plugin/Observer call, not sure what would be the best implementation.

I believe that there can be some place for plugin or observer to do similar trick as I did before. But you will end up with performance downgrade due to possible amount of listed products. And I will not investigate such option because of that reason.

I think my patches found right spot to change query. It just needs to be done right.

**Comment by Djohn12** [comment]
Thanks for the feedback !

I'll try playing with that collection this afternoon then, I'll keep you in touch

**Comment by Djohn12** [comment]
After some debugging in `magento/module-inventory-catalog/Model/ResourceModel/AddStockDataToCollection.php` : 

- Since we `SUM()` the reservations I believe we have to use a `GROUP BY` instruction in order to get distinct rows for each products.
- Since `SUM()` will return `NULL` on product not having any reservations yet, the comparison `> 0` always returned `FALSE`. I added an `IFNULL()` condition for that case.

Here's my new version of your patch on `magento/module-inventory-catalog/Model/ResourceModel/AddStockDataToCollection.php`, this does seem to do the trick on category pages

[github-issue-3062-category-page.zip](https://github.com/magento/inventory/files/8798225/github-issue-3062-category-page.zip)

I believe we just need to apply the same adjustments on `magento/module-inventory-indexer/Model/ResourceModel/GetStockItemData.php` ?

Do you already know where the calls of `GetStockItemData` would be used in favor of `AddStockDataToCollection` ?

**Comment by Djohn12** [comment]
Hi,

I believe my version of the patch was malformed, here is the version we can apply using composer
[github-issue-3062-category-page.zip](https://github.com/magento/inventory/files/8803570/github-issue-3062-category-page.zip)

**Comment by Djohn12** [comment]
Hi @greezlu,

Any update on this ? Did check out my changes ?
Don't want to put any pressure, just not sure you've been notified of my last messages :sweat_smile: 

Have a great day

**Comment by greezlu** [comment]
@Djohn12 Yeah, I like your solution. I tested and it works fine. Feel free to find any new ways to test it.
Basically there's four scenarios to test:

1. Single product default stock.
2. Single product custom stock.
3. Collection default stock.
4. Collection custom stock.

So feel free to test any of them.

---
> Do you already know where the calls of GetStockItemData would be used in favor of AddStockDataToCollection ?

`Magento\InventoryIndexer\Model\IsProductSalable:47`

Final patches
---
**For collections:**
`magento/module-inventory-catalog`
[github-issue-3062-1.patch.zip](https://github.com/magento/inventory/files/8830046/github-issue-3062-1.patch.zip)

**For single product:**
`Module: magento/module-inventory-indexer`
[github-issue-3062-2.patch.zip](https://github.com/magento/inventory/files/8830048/github-issue-3062-2.patch.zip)

Disabling cache for single product
---
Single product stock data is being cached by additional "class layer" preference in `di.xml` for `GetStockItemDataInterface`.
I think that such cache will make our changes not visible, so I disabled those preferences. Feel free to remove it. But I'll remove it from PR.

**Comment by antondkv** [comment]
As I understood why this problem still exists because Magento tries to rewrite the Catalog Inventory module with Inventory Catalog but hasn't done it yet. So this problem isn't prioritized but imho

Attached the module that fixed this issue in more clean way 
[GetStockReserved.tar.gz](https://github.com/magento/inventory/files/9004426/GetStockReserved.tar.gz)

**Comment by ant0x64** [comment]
As I understood why this problem still exists, Magento tries to rewrite the Catalog Inventory module regarding Multi Inventory Sources but hasn't done it yet. So this problem isn't prioritized but imho

Attached the module that fixed this issue in more clean way

<s>[GetStockReserved.tar.gz](https://github.com/magento/inventory/files/9004426/GetStockReserved.tar.gz)</s>
[InventoryIndexerPatch.tar.gz](https://github.com/magento/inventory/files/9011663/InventoryIndexerPatch.tar.gz)

**Comment by marwan-corals** [comment]
@antondkv we got errors on shipment creation related to ReindexOnReserved, 

DDL statements are not allowed in transactions at /var/www/vhosts/tatayab.com/dev/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php:530)"} []
 after debugging it turned out its due to the table below 

RENAME TABLE inventory_stock_3 TO inventory_stock_3_outdated,inventory_stock_3_replica TO inventory_stock_3,inventory_stock_3_outdated TO inventory_stock_3_replica

I think the solution is not elegant as reindexing the entire stock on the change of one SKU is not efficient at all

**Comment by greezlu** [comment]
Don't think this will ever be reviewed.

**Comment by abdulrafaywaqar** [comment]
This patch is working fine just need to change modify minor changes
1.GetStockItemData.php  Group By from **product_id** to **sku** Line#150
2.Both files Before SUM use COALESCE if there is no reservation it should return 0 rathen than null

**Pull request closed without merging**
