### PR TITLE
#2002 Fix problem with reindex even 'Update by Schedule' mode

### PR DESCRIPTION
**Pull request by TadeuRodrigues**
#2002

### CODE REVIEW

**Comment by k4emic** [comment]
Please note that checking for reindex schedule might not be the best option here: https://github.com/magento-engcom/msi/issues/2002#issuecomment-459662076

**Comment by TadeuRodrigues** [comment]
@k4emic i wiil try find some another way, thanks.

**Comment by ishakhsuvarov** [comment]
@smoskaluk Did you check scenario described here: https://github.com/magento-engcom/msi/issues/2002#issuecomment-459662076 ?

While initial case seems to be fixed by this PR, there might be more tricky cases around this feature.

**Comment by smoskaluk** [comment]
Hi @TadeuRodrigues,  the comment by @k4emic is correct, we face problem that after making shipment for order we have wrong salable qty until scheduled cron do reindex, so overselling is possible. May you please reconsider your solution here?

**Comment by TadeuRodrigues** [comment]
@smoskaluk yes of course, thank u, i will try a new approach.

**Comment by ishakhsuvarov** [comment]
@TadeuRodrigues Thank you for working on this 👍 

I'm closing this PR now, as it seems that this exact solution would not cover 100% of cases. Please feel free to submit a new one if you have other solutions!

**Comment by TadeuRodrigues** [comment]
@ishakhsuvarov hi, i have a new solution to this problem, im working now.

**Pull request closed without merging**
