### PR TITLE
Async salable status. Backport of magento/inventory#305

### PR DESCRIPTION
**Pull request by sidolov**
### Fixed Issues (if relevant)

1. Fixes magento/inventory#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run all tests

**Comment by smoskaluk** [comment]
Hi @sidolov , it works, but still after order cancellation reindex is needed

**Comment by smoskaluk** [comment]
Hi @sidolov . PR works, but still after order cancellation index doesn't work

**Comment by sidolov** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests EE,Functional Tests B2B,Functional Tests CE

**Comment by sidolov** [comment]
@magento run WebAPI Tests,Unit Tests,Static Tests,Semantic Version Checker,Magento Health Index,Integration Tests

**Pull request merged**
