### PR TITLE
#1584 Fix UX Text - Max Actions Transfer Inventory to Source

### PR DESCRIPTION
**Pull request by jonatanrdsantos**
### Description (*)

Changed the text's descxribed on the issue #1584

### Fixed Issues (if relevant)

1. magento/inventory#1584: UX Text - Max Actions Transfer Inventory to Source

### Manual testing scenarios (*)

1. Try a mass action inventory to source
2. Try a bulk transfer.
3. Try to select the same origin and destination
### Questions or comments

N/A
### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by joridos** [comment]
@magento give me test instance

**Comment by novikor** [comment]
@magento run all tests

**Review by novikor — CHANGES_REQUESTED** [review]
Hi, @joridos. Thank you for your contribution!
Are you sure the point 3 is implemented?
```
Edit the checkbox content: Unassign the origin source from selected products after transfer.
```

**Comment by jonatanrdsantos** [comment]
@novikor Fixed, sorry I forget that one

**Review by novikor — COMMENTED** [review]
Thank you, @joridos, - looks fine.
However, as far as I see, the `Unassign the origin source from selected products after transfer` text is present in translation file only, - if you are sure it is displayed correctly, OK.

Let's wait for the test builds results.

**Comment by jonatanrdsantos** [comment]
@novikor I forget to add the phtml, fixed now.

**Comment by sidolov** [comment]
@magento run Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run Unit Tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B

**Comment by smoskaluk** [comment]
@joridos Please fix this message 
image
and also error message should be different 
image

 like mentioned here
image

**Pull request merged**
