### PR TITLE
Fix product is not shown on category page if the product is not assigned to any source and "display out stock" is "Yes"

### PR DESCRIPTION
**Pull request by bubasuma**
Fix product is not shown on category page if the product is not assigned to any source and "display out stock" is "Yes"

### Description (*)

If a product is assigned to a website and not assigned to the inventory source assigned to that website, the product will not be listed under category page if "Display Out of Stock Products" is set to "Yes". 

NOTE: This issue is reproducible only with websites assigned to non default source.
### Manual testing scenarios (*)

1. Set _Catalog > Inventory > Stock Options >>Display Out of Stock Products=Yes_
2. Create second website with a store and store view
3. Create second inventory source
4. Create second stock and assign second website and second source
5. Create a product and assign to default website and second website. DO NOT assign any source
6. Create a sub category and assign product created at step#5
7. Go to default website storefront and navigate to category created at step#6
8. Check that product created at step#5 is shown as out of stock
9. Go to second website storefront and navigate to category created at step#56
10. Check that product created at step#5 is not shown

🔴 Actual Result
Product created at step#5 is not shown on second website
🟢 Expected Result
Product created at step#5 is shown on both websites as _out of stock_

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by bubasuma** [comment]
@magento run all tests

**Comment by bubasuma** [comment]
@magento run all tests

**Comment by bubasuma** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by bubasuma** [comment]
@magento run all tests

**Pull request merged**
