### PR TITLE
MQE-2113: fix errors reported by the annotation static check

### PR DESCRIPTION
**Pull request by jilu1**
### Description (*)

[MQE-2123](https://jira.corp.magento.com/browse/MQE-2113): Fix errors reported by the annotation static check

### Fixed Issues (if relevant)

1. magento/inventory#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by jilu1** [comment]
@sidolov This PR is to change mftf tests annotations. Please let me know if you need anything from my side. Thanks!

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Functional Tests EE

**Review by sidolov — APPROVED** [review]

**Pull request merged**
