### PR TITLE
#2851 : Return to Stock checkbox is applied for all products from order not only for selected

### PR DESCRIPTION
**Pull request by konarshankar07**
### Fixed Issues (if relevant)

1. magento/inventory#2851: Return to Stock checkbox is applied for all products from order not only for selected

### Manual testing scenarios (*)

1. Login as customer
2. Add two simple products to cart
3. Place order
4. Create invoice and shipment
5. Check Quantity and Salable Quantity decrease by 1 for appropriate products
image

6. Click `Credit Memo` on order page in admin
7. Check `Return to Stock` only for one product
image
8. Click `Refund Offline`

### Expected Result
Only the product selected `Return to Stock` selected will update the qty
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by konarshankar07** [comment]
Hello @sidolov ...
Do I need to write the MFTF test for this fixed issue?
Thanks

**Comment by konarshankar07** [comment]
Hello @smoskaluk ...
Can you please explain the failure scenario?
Thanks

**Comment by smoskaluk** [comment]
Hi @konarshankar07 ! I tested case the similar as you discribe in this ticket, but without shipping, and get weird result 
image

May you please merge last changes from the mainline in your PR?

**Comment by konarshankar07** [comment]
Hello @smoskaluk ...
I have tested again and I'm not able to reproduce the issue as per your screenshot. Please check the below video 
https://www.loom.com/share/3fbbd2cfcc684a3c87fc7abaf36e5fbe
Thanks

**Pull request closed without merging**
