### PR TITLE
Accept city as null during creating CreditMemo

### PR DESCRIPTION
**Pull request by mamsincl**
### Description (*)

When placing order without any address data, we can invoice, ship but cannot refund

### Fixed Issues (if relevant)

1. magento/inventory#3095: InventorySourceSelection Address model expects city to be string while it can be NULL

### Manual testing scenarios (*)

1. tested with patched local M 2.3.5 instance
2. placing order without specifying city
3. invoice
4. refund

### Questions or comments

NA

### Contribution checklist (*)
 - [+] Pull request has a meaningful description of its purpose
 - [+] All commits are accompanied by meaningful commit messages
 - [+] All new or changed code is covered with unit/integration tests (if applicable)
 - [?] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by mamsincl** [comment]
cc @brucemead

**Comment by mamsincl** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by mamsincl** [comment]
Thanks @smoskaluk @sidolov @magento

**Pull request merged**
