### PR TITLE
#2816 : "This is a required field" error is shown after assigning source to the product

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the required field issue even if the input field have default value
### Fixed Issues (if relevant)

1. magento/inventory#2816: "This is a required field" error is shown after assigning source to the product

### Manual testing scenarios (*)

1. Create a new source
2. Open product edit page
3. Click on "Assign sources" button
4. Select the source from the first step to add
5. Click on "Done" in the modal to assign a source to the product
6. Check, that product qty for that source qty = 0.

### Expected Result
There will be no error
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by sidolov — DISMISSED** [review]

**Comment by sidolov** [comment]
Hi @konarshankar07 , we just checked the solution and we still have a message "This is a required field" on the grid. It looks like the `required-entry` validation is a cause of the message, could you please take a look?

**Review by sidolov — CHANGES_REQUESTED** [review]
Still reproducing

**Comment by konarshankar07** [comment]
Hello @sidolov ...
I found that validation is executing before the setting the default value which is the reason that you are still able to reproduce the issue. Sorry, I missed the changes to commit. Please test now and let me know your feedback
Thanks

**Comment by smoskaluk** [comment]
@konarshankar07 It works now, thank you!

**Review by sidolov — APPROVED** [review]

**Pull request merged**
