### PR TITLE
MSI: 424: Unskip and fix \Magento\Catalog\Controller\ProductTest::testViewActionConfigurable

### PR DESCRIPTION
**Pull request by RomaKis**
Issue: https://github.com/magento-engcom/msi/issues/424

### CODE REVIEW

**Comment by RomaKis** [comment]
This issue will be fixed in https://github.com/magento-engcom/msi/pull/411. Waiting when it will be merged.

**Comment by orlangur** [comment]
Would be better to move https://github.com/magento-engcom/msi/issues/424 into https://github.com/magento-engcom/msi/issues/385 then and do such unskip in https://github.com/magento-engcom/msi/pull/411 itself.

**Review by orlangur — CHANGES_REQUESTED** [review]
Would be better to move https://github.com/magento-engcom/msi/issues/424 into https://github.com/magento-engcom/msi/issues/385 then and do such unskip in https://github.com/magento-engcom/msi/pull/411 itself.

**Comment by naydav** [comment]
Test is not fixed

**Pull request closed without merging**
