### PR TITLE
#348 Removed Priority from Source entity

### PR DESCRIPTION
**Pull request by roma-glushko**
**For now, Pull Request is created to track results of change testings by Travis CI. 
Will be available for review as soon as possible.**

Moved Priority from the Source Entity to StockSourceLink one. 

### Fixed Issues (if relevant)
1. https://github.com/magento-engcom/msi/issues/348: Add priority to StockSourceLink

### ToDo:
- [x] Remove priority from Source entity
- [x] Remove priority from grids
- [x] Remove priority from forms
- [x] Add priority to StockSourceLink entity
- [x] Adjust Assign Source grid on the Stock Edit Form
- [x] Refactor the StockSourceLink validation
- [x] Implement drag & drop feature for the link rows in the Stock Source Link grid
- [ ] Cover Processor classes by integration tests

### CODE REVIEW

**Comment by orlangur** [comment]
@roma-glushko,

> Need to change form, grid, tests

I don't see changes related to form and grid - is priority already not a part of grid/form?

**Comment by roma-glushko** [comment]
@orlangur ,
> For now, Pull Request is created to track results of change testings by Travis CI.
Will be available for review as soon as possible.

Yes, but the reason of creating PR now is mentioned in the description. Let's go this way if you don't mind

**Comment by orlangur** [comment]
@roma-glushko I believe it's easier to find priority declarations with grep than find them out from broken tests :)

Please add something like

- [ ] Remove priority from grids
- [ ] Remove priority from forms

so that it will be not missed and proceed via whatever approach you think is best suitable.

**Comment by roma-glushko** [comment]
@orlangur , Checklist has been added. Thank you for suggestion!

**Review by naydav — APPROVED** [review]

**Pull request merged**
