### PR TITLE
Msi 2003

### PR DESCRIPTION
**Pull request by maghamed**
#2003 

Fix for #2004 PR

### CODE REVIEW

**Comment by GovindaSharma** [comment]
hi @maghamed i have fixed my PR #2004 mistake in latest PR #2008

**Comment by maghamed** [comment]
@GovindaSharma your PR #2008 is not complete as it does not fix an issue for `GetInventoryRequestFromOrder.php` as current PR does. 

Your initial PR #2004 is merged. Thus it's counted as your contribution and contribution points would be granted to you. 

Taking into account that current PR (#2007) is created earlier than yours #2008 and contains a complete fix - it would be merged as soon as @smoskaluk will confirm that problem has gone.

#2008 would be closed as it duplicates 2007.

**Comment by GovindaSharma** [comment]
@maghamed thanks for your update.Actually i wanted to be member of msi repo that's why  i wanted my pr to get merge.But neverthless i will try with any other issue.If you have any issue to suggest me please suggest me i will fix that.Once again thank you.

**Comment by smoskaluk** [comment]
Hi, @maghamed 
I've got error during new source creation
[Thu Jan 31 14:45:11.872175 2019] [php7:error] [pid 1512] [client 127.0.0.1:57568] PHP Fatal error:  Uncaught RuntimeException: Can't create directory /var/www/html/magento2ce/var/generation/Magento/Framework/App/ResourceConnection/Con
fig/. in /var/www/html/magento2ce/lib/internal/Magento/Framework/Code/Generator.php:115\nStack trace:\n#0 /var/www/html/magento2ce/lib/internal/Magento/Framework/Code/Generator/Autoloader.php(35): Magento\\Framework\\Code\\Generator->g
enerateClass('Magento\\\\Framewo...')\n#1 [internal function]: Magento\\Framework\\Code\\Generator\\Autoloader->load('Magento\\\\Framewo...')\n#2 [internal function]: spl_autoload_call('Magento\\\\Framewo...')\n#3 /var/www/html/magento
2ce/lib/internal/Magento/Framework/ObjectManager/Relations/Runtime.php(38): class_exists('Magento\\\\Framewo...')\n#4 /var/www/html/magento2ce/lib/internal/Magento/Framework/Interception/Config/Config.php(153): Magento\\Framework\\Obje
ctManager\\Relations\\Runtime->has('Magento\\\\Framewo...')\n#5 /var/www/html/magento2ce/lib/internal/Magento/Framework/Interception/Config/Config.php(176): Magento\\Framework\\Interception\\Config\\Config->_inheritIn in /var/www/html/
magento2ce/lib/internal/Magento/Framework/Code/Generator.php on line 115
[Thu Jan 31 14:45:34.330417 2019] [php7:error] [pid 2576] [client 192.168.33.1:43852] PHP Fatal error:  Uncaught Error: Call to undefined method Magento\\InventorySourceSelection\\Model\\Address::getStreetAddress() in /var/www/html/mag
ento2ce/pr2/app/code/Magento/InventoryDistanceBasedSourceSelection/Model/Convert/AddressToString.php:23\nStack trace:\n#0 /var/www/html/magento2ce/pr2/app/code/Magento/InventoryDistanceBasedSourceSelection/Model/DistanceProvider/Google
Map/GetLatLngFromAddress.php(103): Magento\\InventoryDistanceBasedSourceSelection\\Model\\Convert\\AddressToString->execute(Object(Magento\\InventorySourceSelection\\Model\\Address))\n#1 /var/www/html/magento2ce/pr2/app/code/Magento/In
ventoryDistanceBasedSourceSelectionApi/Model/GetLatLngFromAddress.php(69): Magento\\InventoryDistanceBasedSourceSelection\\Model\\DistanceProvider\\GoogleMap\\GetLatLngFromAddress->execute(Object(Magento\\InventorySourceSelection\\Mode
l\\Address))\n#2 /var/www/html/magento2ce/pr2/app/code/Magento/InventoryDistanceBasedSourceSelection/Model/DistanceProvider/GetLatLngFromSource.php(70): Magento\\InventoryDistanceBasedSourceSelectionApi\\Model\\Ge in /var/www/html/mage
nto2ce/pr2/app/code/Magento/InventoryDistanceBasedSourceSelection/Model/Convert/AddressToString.php on line 23, referer: http://msi71.vg/pr2/admin/inventory/source/new/key/884e71b690fc6b7a81746d71257db2bc3d60ca24f8572050a8dceaca2239b45
b/
Please recheck

**Comment by maghamed** [comment]
@smoskaluk  fixed, please chack once again

**Pull request merged**
