### PR TITLE
[TSG] Fixes for 2.3 (pr87) (1.1.4-develop)

### PR DESCRIPTION
**Pull request by zakdma**
### Bug - P0
* [MC-29035](https://jira.corp.magento.com/browse/MC-29035) Can't do full reindex 

### Bamboo CI builds

* [x] [Performance Acceptance Test](https://bamboo.corp.magento.com/browse/MCCE23-PAT4092/latest)

### Related Pull Requests

- CE https://github.com/magento/magento2ce/pull/5067
- EE https://github.com/magento/magento2ee/pull/2073
- B2B https://github.com/magento/magento2b2b/pull/871

### CE Checklist

- [ ] PR is green on M2 Quality Portal
- [ ] Jira issues have accurate summary, meaningful description and have links to relevant documentation at the story/task level
- [ ] Semantic Version build failure is approved by architect (if build is red) <Architect Name>
- [ ] Pull Request approved by architect <Architect Name>
- [ ] Pull Request quality review performed by <name>
- [ ] All unstable functional acceptance tests are isolated (if any)
- [ ] All linked Zephyr tests are approved by PO and have Ready to Use status
- [ ] Travis CI build is green (for mainline CE only)
- [ ] Jenkins Unit, Extended FAT CE, Extended FAT EE and Extended FAT B2B builds are green

Created by : @zakdma
Internal PR: https://github.com/magento-tsg/inventory/pull/4

### CODE REVIEW

**Comment by zakdma** [comment]
@magento run Integration Tests

**Comment by zakdma** [comment]
@magento run Functional Tests B2B

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests CE, Unit Tests

**Comment by ishakhsuvarov** [comment]
Static test failure is expected, as mainline was added to the PR.

**Pull request merged**
