### PR TITLE
MC-19640: Multi-Source Inventory shows As Low as $0 for configurable products in frontend

### PR DESCRIPTION
**Pull request by namlier**
### Description (*)
The problem was in lowest price of configurable product determination. 
Magento\ConfigurableProduct\Pricing\Price\LowestPriceOptionsProvider uses LinkedProductSelectBuilder to find links of the configurable using "stock status" filtration. But the Magento wasn't configured to take into account the MSI implementation, so it was impossible to find simple products in the default stock.

### Manual testing scenarios (*)
1) Make sure "Admin > Stores > Configurations > Catalog > Inventory > Stock Options > Display Out of Stock Products" is set to true:
2) Create a new inventory source
3) Create a new inventory stock and add the website as the sales channel.
4) Assign the created source to the created stock
5) Create a configurable product with multiple simple products and assign them to the newly created
inventory source.
6) Add quantity to > 0 and stock status to in stock
7) Validate the product on front-end

EXPECTED RESULTS:
The configurable Product should show As low as the lowest price of the associated simple products

ACTUAL RESULTS:
The configurable Product shows As low as $0.00

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
Hi @mastiuhin-olexandr 

Thank you for the PR. Detailed description really helps. Could you please also provide some sort of automated test covering this behavior with default and custom stocks?

Thanks

**Comment by namlier** [comment]
> 
> 
> Hi @mastiuhin-olexandr
> 
> Thank you for the PR. Detailed description really helps. Could you please also provide some sort of automated test covering this behavior with default and custom stocks?
> 
> Thanks

Of course, i just wanted to try this on tests before. Soon ill cover it with integration test.

**Comment by ishakhsuvarov** [comment]
Thanks

**Comment by ishakhsuvarov** [comment]
@mastiuhin-olexandr Please let us know when you have time to add some tests to the Pull Request.

Thanks!

**Comment by ishakhsuvarov** [comment]
@mastiuhin-olexandr Thanks. I'll proceed with review shortly

**Review by ishakhsuvarov — APPROVED** [review]

**Pull request merged**
