### PR TITLE
1539 move source dropdown values to a separated class

### PR DESCRIPTION
**Pull request by LeonidTomashevskyAmasty**
### Description

1. Sorce dropdown values should be in a separated class
2. Source Selection Algorithm in \Magento\InventoryShippingAdminUi\Ui\DataProvider\SourceSelectionDataProvider should be the same as in `\Magento\InventoryShippingAdminUi\Controller\Adminhtml\SourceSelection\ProcessAlgorithm`

### Fixed Issues (if relevant)

1. https://github.com/magento-engcom/msi/issues/1539: Refactoring: Move the Source dropdown values to a separate class

### Manual testing scenarios

1. Assign the Sources to the products
2. Create a Order with 2+ items
3. In the Order view Press "Ship"
4. "Source Selection" page should open.
Source dropdown shoud have sorted sources

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=1540) <br/>All committers have signed the CLA.

**Comment by LeonidTomashevskyAmasty** [comment]
@magento-engcom-team come on guys, I have deserved at least a reason why you close my PR. I did hard working on it and it just waiting for review 3 month

**Comment by maghamed** [comment]
hey @LeonidTomashevskyAmasty sorry, it was closed by mistake with automated tool.

Just reopened your PR again

**Comment by novikor** [comment]
Hi, @LeonidTomashevskyAmasty .
Thank you for your contribution. It would be great if you resolve the conflicts

**Comment by LeonidTomashevskyAmasty** [comment]
After discussion with @novikor we decided just to close this PR. For now the changes is not relevant (the changes contain class and arguments deleting which will broke backward compatibility).

**Pull request closed without merging**
