### PR TITLE
MSI-3066: Product not appears on category page when async Stock / Source indexer enabled.

### PR DESCRIPTION
**Pull request by nmalevanec**
### Fixed Issues (if relevant)

1. https://github.com/magento/inventory/issues/3066: Product not appears on category page when async Stock / Source indexer enabled

### Manual testing scenarios (*)

1. see https://github.com/magento/inventory/issues/3066

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by nmalevanec** [comment]
@magento run all tests

**Comment by nmalevanec** [comment]
@magento run all tests

**Comment by nmalevanec** [comment]
@magento run all tests

**Comment by nmalevanec** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Pull request merged**
