### PR TITLE
Msi 2027 improve performance product save operation

### PR DESCRIPTION
**Pull request by phoenix128**
### Description (*)
FIX for performance regression of previously merged PR

### Fixed Issues (if relevant)
1. magento-engcom/msi#2027: Msi 2027 improve performance product save operation

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by novikor** [comment]
Hi, @phoenix128 .

I forced to decline this PR: `inventory_source_item` table is not updated after QTY is updated using the Admin Panel.

**Comment by novikor** [comment]
**Test scenario:**
- Go to a product edit page: Admin Panel -> Catalog -> Products -> Any product
- Does not matter if the default stock/source is used or not
- Update QTY and save changes

**Expected result:**
QTY is updated
**Actual result:**
It is not

**Review by novikor — CHANGES_REQUESTED** [review]
Please check the test scenario. Thank you.

**Comment by ishakhsuvarov** [comment]
@novikor This Pull Request is not complete. Changes from https://github.com/magento-engcom/msi/pull/2056 have to be reapplied for the full picture.

**Comment by ishakhsuvarov** [comment]
Updating the branch once more to run performance tests on internal infrastructure.

**Comment by ishakhsuvarov** [comment]
Hi @phoenix128 

Unfortunately performance tests still show degradation, even with the patch applied. I think there was another observer or plugin doing double sync. 

<details>

```
loaded-classes
New Bundle Product Save (Admin Create Product): 6.2% (mainline = 1858 | team = 1973) -> DEGRADATION
New Configurable Product Save (Admin Create Product): 5.1% (mainline = 1879 | team = 1975) -> DEGRADATION
Edit Configurable Product Save (Admin Edit Product): 6.2% (mainline = 1868 | team = 1983) -> DEGRADATION
Save Shipment (Admin Create Order): 5.9% (mainline = 1751 | team = 1855) -> DEGRADATION
Import Start (Import Products): 6.8% (mainline = 1578 | team = 1685) -> DEGRADATION
New Bundle Product Save (Catalog GraphQL): 6.2% (mainline = 1844 | team = 1959) -> DEGRADATION

tideways-mysql-delete-requests-count
Credit Memo Submit - Full Refund (Admin Returns Management): 83.3% (mainline = 6 | team = 11) -> DEGRADATION
Save Shipment (Admin Create Order): 72.7% (mainline = 11 | team = 19) -> DEGRADATION
Create Shipment (API Process Orders): 83.3% (mainline = 6 | team = 11) -> DEGRADATION

tideways-mysql-insert-requests-count
Credit Memo Submit - Full Refund (Admin Returns Management): 33.3% (mainline = 15 | team = 20) -> DEGRADATION
Save Shipment (Admin Create Order): 47.1% (mainline = 17 | team = 25) -> DEGRADATION
Create Shipment (API Process Orders): 41.7% (mainline = 12 | team = 17) -> DEGRADATION

tideways-mysql-update-requests-count
Clear Wishlist 4 (Add to Wishlist): 100% (mainline = 1 | team = 2) -> DEGRADATION
```

**Comment by novikor** [comment]
Hi, @phoenix128 .
Please check the previous comment from @ishakhsuvarov

**Review by novikor — DISMISSED** [review]

**Review by novikor — CHANGES_REQUESTED** [review]
Hi, @phoenix128 .
Please check the previous comment from @ishakhsuvarov

**Comment by novikor** [comment]
Thank you for your contribution, we do appreciate that.
Unfortunately, the PR is closed due to inactivity.
Please feel free to reopen it if you wish.

**Pull request closed without merging**
