### PR TITLE
Disabled variation of configurable product can be added to shopping cart via admin

### PR DESCRIPTION
**Pull request by VeronikaYarats**
### Bug
* [MAGETWO-72172](https://jira.corp.magento.com/browse/MAGETWO-72172) [2.3] Disabled variation of configurable product can be added to shopping cart via admin

### Bamboo CI Builds
* [x] [M2, CI (CE + EE) - 2.3-develop - Performance Acceptance Test](https://bamboo.corp.magento.com/browse/MCCE23-PAT3673/latest)

### Related Pull Requests
https://github.com/magento/magento2ce/pull/4925
https://github.com/magento/magento2ee/pull/2019

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2609) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2609) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: VeronikaYarats<br/>:x: epamt

**Comment by ishakhsuvarov** [comment]
@VeronikaYarats Please update Pull Request description with information on what is it intended to do and instructions on merge. Also, please squash commits, we have too much commits for a single file.

Thanks

**Comment by irenelagno** [comment]
@VeronikaYarats, please sign in Adobe CLA

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests build, Integration Tests build

**Pull request merged**
