### PR TITLE
Inventory In-Store Pickup

### PR DESCRIPTION
**Pull request by ishakhsuvarov**

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run Magento Health Index

**Comment by sidolov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Integration Tests,Unit Tests

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run Integration Tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Integration Tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Integration Tests

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests CE,Integration Tests

**Comment by sidolov** [comment]
@magento run Integration Tests

**Comment by sidolov** [comment]
@magento run Integration Tests

**Pull request merged**
