### PR TITLE
Fix extensibility for \Magento\InventorySales\Test\Api\OrderPlacementBase abstract class.

### PR DESCRIPTION
**Pull request by vpodorozh**
### Description
Was requested here: #2606
Just changing `private` to `protected` for properties and methods for Base abstract API test class that is used as a parent for all `OrderPlacement*` API tests for MSI.

That sounds logical to make it extensible for child classes in case something needs to be changed in methods implementation (see #2606 as an example )

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by swnsma** [comment]
@vpodorozh,
Could you sign Adobe CLA?

**Comment by vpodorozh** [comment]
> @vpodorozh,
> Could you sign Adobe CLA?

done

**Review by swnsma — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Integration Tests build

**Pull request merged**
