### PR TITLE
Load product salability data on demand

### PR DESCRIPTION
**Pull request by swnsma**
### Description (*)
Stop stock data load on after load event.
Inheritance of https://github.com/magento/inventory/pull/3039

See #3202 
### Fixed Issues (if relevant)
1. https://github.com/magento/inventory/issues/3201

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by swnsma** [comment]
@magento run all tests

**Comment by novikor** [comment]
@magento run Integration Tests

**Comment by novikor** [comment]
@magento run Static Tests

**Comment by novikor** [comment]
Let's close it in favor of #3208

**Pull request closed without merging**
