### PR TITLE
Msi 2631 Source selector disappear in store pickup orders placement from admin panel

### PR DESCRIPTION
**Pull request by novikor**
### Description (*)
Now after the shipping method reset (In case 'Save in address book' for country fields are changed)
In-Store Pickup shipping method is selected if it previously was.

### Fixed Issues (if relevant)
1. https://github.com/magento/inventory/issues/2631 Source selector disappear in store pickup orders placement from admin panel

### Manual testing scenarios (*)
1. Place order with your product in admin area
2. Select 'In-Store Pickup Delivery' as shipping method 
3. Verify that drop-down list for 'Pickup Location Source' selection appear 
4. Uncheck box 'Save in address book' for your billing address
5. Make Sure 'In-Store Pickup Delivery' is still selected and the sources list is visible

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by swnsma — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run Functional Tests Unit Tests

**Comment by sidolov** [comment]
@magento run Functional Tests

**Comment by sidolov** [comment]
@magento run Unit Tests

**Comment by novikor** [comment]
@magenro run Functional Tests

**Comment by novikor** [comment]
@magento run Functional Tests

**Comment by novikor** [comment]
@magento run Unit Tests

**Comment by sidolov** [comment]
@magento run Unit Tests

**Comment by sidolov** [comment]
@magento run Unit Tests

**Review by sidolov — APPROVED** [review]

**Pull request merged**
