### PR TITLE
Place In-Store Pickup Order with Webapi tests coverage #2586

### PR DESCRIPTION
**Pull request by vpodorozh**
Place In-Store Pickup Order with Webapi tests coverage #2586

### Description (#2586)
Please add webapi tests for order placement with In-Store Pickup.
- [x] Place In-Store Pickup Order as Guest
- [x] Place In-Store Pickup Order as Logged In user with new address
- [x] Place In-Store Pickup Order as Logged In user with customer address
- [x] Place In-Store Pickup Order as Logged In user and try to save shipping address to address book.
- [x] Place In-Store Pickup Order and try to use 'Billing the same as shipping' option.

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by ishakhsuvarov** [comment]
@magento run Functional Tests build

**Comment by vpodorozh** [comment]
@ishakhsuvarov - could you advice on static tests issue with copy&paste?
I case it is possible to change MSI in scope of `store-pickup` branch that I can resolve this problem. But in case it is forbidden - I suggest to skip this issue.

**Comment by swnsma** [comment]
@ishakhsuvarov, @vpodorozh 
May we should change properties of `\Magento\InventorySales\Test\Api\OrderPlacementBase`
from `private` to `protected` ?

**Comment by ishakhsuvarov** [comment]
I agree. Let's change it in 2.3-develop

**Review by ishakhsuvarov — CHANGES_REQUESTED** [review]
Let's resolve static test failures by adjusting abstract test class.

**Comment by swnsma** [comment]
Hi @vpodorozh,
Will you continue with this PR?

**Comment by vpodorozh** [comment]
@swnsma - Sunday evening

**Comment by swnsma** [comment]
Related PR has been merged.
@ishakhsuvarov, now we need to have it in `store-pickup` branch.

**Comment by sidolov** [comment]
@vpodorozh could you take a look at failed tests? Related PR https://github.com/magento/inventory/pull/2643 already merged

**Comment by vpodorozh** [comment]
@sidolov - will check it on Monday. Thx!

**Comment by vpodorozh** [comment]
Dear @swnsma , please check failed integration tests. I do not understand why they are failed - no red tests in allure report.

**Comment by sidolov** [comment]
@magento run Functional Tests B2B,Functional Tests EE,WebAPI Tests

**Comment by sidolov** [comment]
@magento run Functional Tests EE,Unit Tests,WebAPI Tests

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run Functional Tests EE

**Review by sidolov — APPROVED** [review]

**Pull request merged**
