### PR TITLE
Do not check for stock when determining price for configurable product when ShowOutOfStock is enabled

### PR DESCRIPTION
**Pull request by alexander-aleman**
### Description (*)

A customer requested to show the price of configurable products, that are out of stock, on the product list page. After creating a plugin for the \Magento\Catalog\Model\Product\Pricing\Renderer\SalableResolverInterface so it allows for configurable products that are out of stock to show a price, I noticed that the price was 0 for all out of stock configurable products., this was caused by the fact that \Magento\InventoryConfigurableProduct\Pricing\Price\LowestPriceOptionsProvider\StockStatusBaseSelectProcessor::process was incorrectly manipulating the $select when show out of stock products is enabled.

### Fixed Issues (if relevant)

1. magento/magento2#<issue_number>: Issue title

### Manual testing scenarios (*)

1. Create a configurable product with an out of stock simple product
2. Enable show out of stock products
3. Make sure \Magento\Catalog\Model\Product\Pricing\Renderer\SalableResolverInterface::isSalable returns true for your product

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by slavvka** [comment]
@magento run all tests

**Comment by smoskaluk** [comment]
Hi @alexander-aleman ! After manual testing I still don't see that price is displaying for out-of-stock configurable product  on product list page. Please recheck.

**Comment by alexander-aleman** [comment]
This changes causes problems for the case when show out of stock products is not enabled.

**Comment by wexo-team** [comment]
@alexander-aleman 
We're experiencing the same issue as you had on a shop of ours. Did you find another way around to fix it without breaking other functionality? It is pretty obvious that there's a logic problem in the method and my initial thoughts was to do the exact same fix as you did.

**Comment by alexander-aleman** [comment]
@wexo-team Unfortunately not, I ended up using my own fix for this case, since we do not vary with the show out of stock setting. And I did not want to spend more time on the issue.

**Pull request closed without merging**
