### PR TITLE
Add caching of result for sql queries

### PR DESCRIPTION
**Pull request by RuslanKostiv1**
### Description (*)

Performance improvements by decreasing of amount of queries.

### Fixed Issues (if relevant)

1. https://github.com/magento/inventory/issues/2929: [Performance improvement] Add caching of result for sql queries
2. added caching of sql queries to `inventory_stock_sales_channel`   
3. removed usage of `AreProductsSalableInterface` where it's not necessary (no need to load all products if we do check for 1st product and executing `break`), replaced with `IsProductsSalableInterface`

### Manual testing scenarios (*)

1. turn on magento logs`bin/magento dev:query-log:enable`
2. execute scenarios `Configurable Product Add To Cart`
3. Compare amount of queries to given tables (in linked issue)

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by mbrinton01 — DISMISSED** [review]
Approved by Product Manager

**Comment by RuslanKostiv1** [comment]
B2B tests related to Paypal failed because of the issue into mainline, those tests will be skipped into further PRs into mainline. Appropriate issue already exists into backlog `MC-33951`

**Comment by RuslanKostiv1** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
B2B failures are random. 
Two builds on the same commits failed with different tests: [Build1](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/inventory/pull/2972/f5594f36b4cc76bb43b8b0be7d80699a/Functional/allure-report-b2b/index.html#suites/8187718e2fd144987673ef34ee62b41b), [build2](https://public-results-storage-prod.magento-testing-service.engineering/reports/magento/inventory/pull/2972/4af1ab15a9b8fa8f36a528da5710632a/Functional/allure-report-b2b/index.html#suites/c1b8c59972484588326cae5ed68f8997/a8605c4523c8eb09/)

**Pull request merged**
