### PR TITLE
Update store pickup with latest changes from core

### PR DESCRIPTION
**Pull request by ishakhsuvarov**
This Pull Request updates `store-pickup` feature branch with the latest changes in `2.3-develop`

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) before we can accept your contribution.<br/>**3** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: mastiuhin-olexandr<br/>:white_check_mark: Stepa4man<br/>:x: serhii-balko<br/>:x: magento-engcom-team<br/>:x: sivaschenko<br/>:x: magento-cicd2<br/>:x: dhaecker<br/>:x: krissyhiserote<br/>:x: joanhe

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) before we can accept your contribution.<br/>**3** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: mastiuhin-olexandr<br/>:white_check_mark: Stepa4man<br/>:x: serhii-balko<br/>:x: magento-engcom-team<br/>:x: sivaschenko<br/>:x: magento-cicd2<br/>:x: dhaecker<br/>:x: krissyhiserote<br/>:x: joanhe

**Comment by swnsma** [comment]
Created ticket according to found issue with Integration tests during the merge: https://github.com/magento/magento2/issues/23974

**Comment by ishakhsuvarov** [comment]
@magento run all tests

**Comment by ishakhsuvarov** [comment]
@magento run Sample Data Tests build

**Comment by ishakhsuvarov** [comment]
@magento run Static Tests build

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) before we can accept your contribution.<br/>**3** out of **10** committers have signed the CLA.<br/><br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: mastiuhin-olexandr<br/>:white_check_mark: Stepa4man<br/>:x: serhii-balko<br/>:x: magento-engcom-team<br/>:x: sivaschenko<br/>:x: magento-cicd2<br/>:x: dhaecker<br/>:x: krissyhiserote<br/>:x: joanhe

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) before we can accept your contribution.<br/>**3** out of **16** committers have signed the CLA.<br/><br/>:white_check_mark: p-bystritsky<br/>:white_check_mark: tomreece<br/>:white_check_mark: nmalevanec<br/>:x: magento-engcom-team<br/>:x: dng-dev<br/>:x: Nikita Fomin<br/>:x: sivaschenko<br/>:x: lenaorobei<br/>:x: magento-cicd2<br/>:x: vital-pantsialeyeu<br/>:x: andimov<br/>:x: textarea<br/>:x: AlexMaxHorkun<br/>:x: gfernandes410<br/>:x: Roman Lytvynenko<br/>:x: bubasuma<hr/>**Nikita Fomin, Roman Lytvynenko** seem not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by slavvka** [comment]
@magento run Magento Component Health Index build

**Comment by slavvka** [comment]
@magento run Magento Health Index build

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2434) before we can accept your contribution.<br/>**3** out of **16** committers have signed the CLA.<br/><br/>:white_check_mark: p-bystritsky<br/>:white_check_mark: tomreece<br/>:white_check_mark: nmalevanec<br/>:x: dng-dev<br/>:x: Nikita Fomin<br/>:x: magento-engcom-team<br/>:x: sivaschenko<br/>:x: lenaorobei<br/>:x: magento-cicd2<br/>:x: vital-pantsialeyeu<br/>:x: andimov<br/>:x: textarea<br/>:x: AlexMaxHorkun<br/>:x: gfernandes410<br/>:x: Roman Lytvynenko<br/>:x: bubasuma<hr/>**Nikita Fomin, Roman Lytvynenko** seem not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Pull request merged**
