### PR TITLE
Fixed issue #2003 POST /V1/inventory/source-selection-algorithm-result payload doesn't accept street_address

### PR DESCRIPTION
**Pull request by GovindaSharma**
### Description
Fixed issue #2003 POST /V1/inventory/source-selection-algorithm-result payload doesn't accept street_address

Fixed issue #2003 POST /V1/inventory/source-selection-algorithm-result payload doesn't accept street_address

### Manual testing scenarios

1.Configure a source so that it can be used with the distance SSA.
2.Create an order and invoice.
3.Run POST /V1/inventory/source-selection-algorithm-result with a payload similar to the following. (The    syntax of the payload was taken from Swagger.)

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2004) <br/>All committers have signed the CLA.

**Comment by smoskaluk** [comment]
Hi @GovindaSharma!
Please recheck your PR, I've got error during creating shipment for order in admin

image

**Comment by maghamed** [comment]
Hey @GovindaSharma would you be able to finish this PR today?

**Comment by maghamed** [comment]
You have to fix usages of `Magento\InventorySourceSelectionApi\Api\Data\AddressInterfaceFactory` as well, for example 

```

namespace Magento\InventoryDistanceBasedSourceSelection\Model\DistanceProvider;



/**
 * Class GetLatLngFromSource
 */
class GetLatLngFromSource
...
    public function execute(SourceInterface $source): LatLngInterface
    {
        if (!$source->getLatitude() || !$source->getLongitude()) {
            $sourceAddress = $this->addressInterfaceFactory->create([
                'country' => $source->getCountryId() ?? '',
                'postcode' => $source->getPostcode() ?? '',
                'streetAddress' => $source->getStreet() ?? '',
                'region' => $source->getRegion() ?? '',
                'city' => $source->getCity() ?? ''
            ]);

```
and other similar places

**Comment by GovindaSharma** [comment]
hello @maghamed yes i wll fix it today

**Pull request merged**
