### PR TITLE
[TSG-Commerce] MC-34459: Add global node to override config

### PR DESCRIPTION
**Pull request by zakdma**
### Bug
* [MC-34459](https://jira.corp.magento.com/browse/MC-34459) Add global node to override config

### Bamboo CI builds

- Not required for tests delivery

### CE Checklist

- [ ] PR is green on M2 Quality Portal
- [ ] Jira issues have accurate summary, meaningful description and have links to relevant documentation at the story/task level
- [ ] Semantic Version build failure is approved by architect (if build is red) <Architect Name>
- [ ] Pull Request approved by architect <Architect Name>
- [ ] Pull Request quality review performed by <name>
- [ ] All unstable functional acceptance tests are isolated (if any)
- [ ] All linked Zephyr tests are approved by PO and have Ready to Use status
- [ ] Travis CI build is green (for mainline CE only)
- [ ] Jenkins Unit, Extended FAT CE, Extended FAT EE and Extended FAT B2B builds are green

Created by : @zakdma
Internal PR: https://github.com/magento-tsg/magento2ce/pull/791

### CODE REVIEW

**Comment by zakdma** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@sidolov all failed B2B tests are flaky ones and described in this ticket
https://jira.corp.magento.com/browse/MC-34516

**Comment by sidolov** [comment]
@magento run all tests

**Comment by zakdma** [comment]
@magento run all tests

**Review by sidolov — APPROVED** [review]

**Pull request merged**
