### PR TITLE
magento/inventory#3071: Change name from in_store to instore.

### LINKED ISSUE #3071: Invalid carrier code?
Hi,

I noticed the following carrier code in the new in-store pickup shipping method:
https://github.com/magento/inventory/blob/92c6817a5ba6bbc7be93092e25af8769c713311e/InventoryInStorePickupShippingApi/Model/Carrier/InStorePickup.php#L33

I believe the assumption that the underscore separates the carrier code from the method code exists in the logic, because I have seen custom carriers break after an upgrade in the past due to the carrier code containing an underscore. Are we sure that this is not still the case? Shouldn't the carrier code simply be "instore" to be on the safe side even if the core code no longer requires that the underscore separate carrier and method codes, just in case some 3rd party or custom code does depend on it?

### PR DESCRIPTION
**Pull request by swnsma**
### Description (*)
Change In Store Pickup name to avoid possible incompatibilities.

### Fixed Issues (if relevant)
1. magento/inventory#3071

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by novikor** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests CE,Integration Tests

**Pull request closed without merging**
