### PR TITLE
Msi 2380 remove dependency on magento sales from inventory in store pickup module

### PR DESCRIPTION
**Pull request by swnsma**
### Fixed Issues (if relevant)

1. https://github.com/magento/inventory/issues/2380: Remove dependency on Magento\Sales from InventoryInStorePickup module

### CODE REVIEW

**Comment by Stepa4man** [comment]
@buskamuza Hi Olga. I think we have to check this error in SVC. The table was moved to another module but, SVC still indicates that it's in db_schema.xml:
image

**Review by Stepa4man — APPROVED** [review]

**Comment by swnsma** [comment]
Branch updated with latest changes from **store-pickup**.

**Review by sidolov — APPROVED** [review]

**Review by Stepa4man — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Pull request merged**
