### PR TITLE
2170 reservation cli compensation

### PR DESCRIPTION
**Pull request by vadimjustus**
- Refactore given logic for collection inconsistencies
- Change CLI, which displays all given inconsistencies
- Introduce CLI command, which creates the compensations

### Description (*)
This PR changes the current implementation for 
- magento-engcom/msi#2140
- magento-engcom/msi#2169

and has dependency to PR https://github.com/magento-engcom/msi/issues/2171

### Fixed Issues (if relevant)
1. magento-engcom/msi#2170: Reservations CLI: Compensation

### Manual testing scenarios (*)
1. Create multiple orders 
2. Ship some orders and create an invoice (completed orders)
3. Remove reservations for DB 
4. Run `bin/magento inventory:reservation:list-inconsistencies` to see the given inconsistencies
5. Run `bin/magento inventory:reservation:create-compensations` to fix the reservation issues

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by smoskaluk** [comment]
Hi @vadimjustus , I've got issue with reservations inconsistencies by next steps:

1.Create product on default stock
2. Place order with it
3. Remove the reservation from database for created order
4. Run bin/magento inventory:reservation:create-compensations to fix the reservation issues
As result such reservation created:
 -1.0000 | {"event_type":"manual_compensation","object_type":"order","object_id":1}
5. Create custom stock with custom source and assign Main website as sales channel
6. Run reindex and flush cache
7. Run bin/magento inventory:reservation:list-inconsistencies

image

**Comment by vadimjustus** [comment]
Hi @smoskaluk, thank you for testing. I can't reproduce the issue in your screenshot. What I've tried is following:
1. Create a product on default stock
2. Checkout the product
3. Remove reservation from database
4. Run `bin/magento inventory:reservation:list-inconsistencies`
```
Inconsistencies found on following entries:
Order 000000001:
  - Product sim1 should be compensated by -1.000000
```
5. Run `bin/magento inventory:reservation:create-compensations`
```
Following reservations were created:
Product sim1 compensated by -1.000000 for stock id 1
```
6. Create custom stock with custom source and assign my website to the custom stock
7. Edit product and assign the new source to it with qty
8. Run full reindex and cache invalidation
9. Run `bin/magento inventory:reservation:list-inconsistencies`
```
Inconsistencies found on following entries:
Order 000000001:
  - Product sim1 should be compensated by -1.000000
```
10. Run `bin/magento inventory:reservation:create-compensations`
```
Following reservations were created:
Product sim1 compensated by -1.000000 for stock id 2
```
11. Run `bin/magento inventory:reservation:list-inconsistencies`
```
No order inconsistencies were found
```

Since reservations contain the `stock_id`, it seems to be correct, that after changing the stock for my sales channel the data show up as inconsistent. Running the compensations is resolving the problem. As a result I have now two reservations for the same order in my database. 
```csv
reservation_id,stock_id,sku,quantity,metadata
2,1,sim1,-1.0000,"{"event_type":"manual_compensation","object_type":"order","object_id":1}"
3,2,sim1,-1.0000,"{"event_type":"manual_compensation","object_type":"order","object_id":1}"
```
But this is correct for saleable quantity calculation point of view.
Screenshot 2019-04-16 23 51 12

**Regarding the `GetStockItemConfiguration.php` error in your screenshot**
Do you have a clean system? There are no changes in this part of MSI in my PR, but there are currently some other Tasks regarding this in progress. Maybe there was a mess?

**Comment by smoskaluk** [comment]
Hi @vadimjustus , the issue is because I did not reassign sim1 to new custom stock - it was assigned to default stock only - and it look strange that I get this message. 
Inconsistencies found on following entries:
Order 000000001:
  - Product sim1 should be compensated by -1.000000

Please try your scenario without step 7.

**Comment by vadimjustus** [comment]
Hi @smoskaluk! Thank you.

I've made an update for this. Your scenario discovered also an issue with SKUs, which has disabled stock management. It's fixed now.

@maghamed probably we need to discuss whether it is an inconsistency if the reservation we have for an order is made on a different stock, because stock of the sales channel was switched. Current solution will ignore this, but let's discuss about it.

**Comment by ishakhsuvarov** [comment]
@vadimjustus The case you have described with the reassignment definitely makes sense. I think it's a good idea to adjust tools to support this scenario and update documentation with this information. Thanks

**Review by ishakhsuvarov — APPROVED** [review]

**Pull request merged**
