### PR TITLE
#2299 : manage stock = no but showing only X left

### PR DESCRIPTION
**Pull request by konarshankar07**
### Description (*)

This PR will fix the bug with message showing for limited stock quantity for product level.
### Fixed Issues (if relevant)

1. magento/inventory#2299: manage stock = no but showing only X left

### Manual testing scenarios (*)

1. Login to Magento Admin
2. Go to Store -> Configuration
3. Expand Catalog menu from left sidebar list
4. Click on Inventory 
5. Expand Stock options
6. Enter "5" in "Only X left Threshold" textfield
7. Go to Catalog -> Product
8. Create new product
9. Enter Quantity 2
10. Click on "Advanced Inventory" link below Quantity field
11. Uncheck "Use Config Settings" checkbox for "Manage Stock"
12. Change "Manage Stock" to "No"
13. Field all the required field and save the product
14. Open the product page in frontend

### Expected Result
There will be no message for the saved product
Screenshot for Manage Stock selected to "NO"
image
Screenshot for other product which has Quantity less than threshold quantity
image

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by sidolov** [comment]
Hi @konarshankar07 thank you for the fix! We have checked it and scenario works as expected. Could you please cover changes with the automated tests to avoid such bugs in the future? Thanks!

**Comment by konarshankar07** [comment]
Hello @sidolov... Which test MFTF or unit test?

**Comment by sidolov** [comment]
@konarshankar07 MFTF would be nice

**Review by sidolov — APPROVED** [review]

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Comment by sidolov** [comment]
@magento run Static Tests

**Comment by sidolov** [comment]
@magento run Functional Tests CE

**Pull request merged**
