### PR TITLE
MAGETWO-44165: [FT] Magento\Catalog\Test\TestCase\Product\ProductType…

### PR DESCRIPTION
**Pull request by YuliyaLabudova**
### Bug
* [MAGETWO-44165](https://jira.corp.magento.com/browse/MAGETWO-44165) [FT] Magento\Catalog\Test\TestCase\Product\ProductTypeSwitchingOnCreationTest fails

### CODE REVIEW

**Comment by smoskaluk** [comment]
Hi @YuliyaLabudova ! The problem is still there.
Step to reproduce:
Create and save simple product with qty = 0 and stock status = 'Out of stock'
Open 'Advanced inventory' from product page in admin - stock status = 'In stock'

**Comment by YuliyaLabudova** [comment]
> Hi @YuliyaLabudova ! The problem is still there.
> Step to reproduce:
> Create and save simple product with qty = 0 and stock status = 'Out of stock'
> Open 'Advanced inventory' from product page in admin - stock status = 'In stock'



> Hi @YuliyaLabudova ! The problem is still there.
> Step to reproduce:
> Create and save simple product with qty = 0 and stock status = 'Out of stock'
> Open 'Advanced inventory' from product page in admin - stock status = 'In stock'



> Hi @YuliyaLabudova ! The problem is still there.
> Step to reproduce:
> Create and save simple product with qty = 0 and stock status = 'Out of stock'
> Open 'Advanced inventory' from product page in admin - stock status = 'In stock'

I have updated. Can you please recheck it?

**Comment by YuliyaLabudova** [comment]
@smoskaluk Can you please recheck it? Now seems it's ok

**Comment by smoskaluk** [comment]
@YuliyaLabudova issue is solved, thank you!

**Pull request merged**
