### PR TITLE
1451 avoid fading assign sources listing when advanced inventory manage stock being changed

### PR DESCRIPTION
**Pull request by VitaliyBoyko**
### Fixed Issues (if relevant)
1. magento-engcom/msi#1451: 
Avoid fading assign sources listing when advanced inventory manage stock being changed

### Steps to reproduce
1. Open product form
2. Click on "advanced inventory"
3. Set manage stock to "No" and click "Done"

### Expected result
Assign sources dynamic rows should be visible, inputs related to stock should be disabled.

### Actual result
assign sources dynamic rows will fade.

### CODE REVIEW

**Comment by smoskaluk** [comment]
@VitaliyBoyko Hi Vitaliy, may you please recheck your PR
1. Problem - in single stock mode on the product page in admin present "Sources' tab 
2. Problem - after creating custom source and then creating simple product and assign to default and custom sources - after save product get 'Mange stock' = No in 'Advanced inventory' (despite that 'Use config settings' is checked) 
image

**Comment by VitaliyBoyko** [comment]
Hi @smoskaluk 
All mentioned issues have been fixed. Thank you!

**Comment by smoskaluk** [comment]
Hi @VitaliyBoyko!  
in single stock mode on the product page in admin "Sources' tab is present again
image

**Comment by VitaliyBoyko** [comment]
Thanks @smoskaluk 
Gonna check it.

**Comment by VitaliyBoyko** [comment]
@smoskaluk I've hidden sources tab in single stock mode instead of hiding source button and dynamic rows.

**Review by maghamed — APPROVED** [review]

**Pull request merged**
