### PR TITLE
Msi 2064 salable qty integration test

### PR DESCRIPTION
**Pull request by josh-carter**
### Description (*)

Adds new Product and Source Item to data fixtures to cover case in #2064, product with:

```
    'qty' => 0,
    'is_in_stock' => true,
    'manage_stock' => true,
    'is_qty_decimal' => true,
    'min_qty' => -3,
    'backorders' => true
```

This is then provided to the existing integration test for `Magento\InventorySalesApi\Api\GetProductSalableQtyInterface` via the dataProvider function.

Test still passes though so maybe #2064 a non issue or a slightly difference circumstance?

### Fixed Issues (if relevant)
1. magento-engcom/msi#2064: Create integration test to check salable qty for product

### Contribution checklist (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [x] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by josh-carter** [comment]
@maghamed This just timed out in Travis on that job it always times out on

**Comment by maghamed** [comment]
@josh-carter looks like except time-out there are broken tests as well. Re-running Integration tests now
```...............SS..F.F..........FF.F......................... 3843 / 4520 ( 85%)
............................................................. 3904 / 4520 ( 86%)
............................F.F.............F.F.FF.FF.FFFFF.. 3965 / 4520 ( 87%)
............................................................. 4026 / 4520 ( 89%)
............................................................. 4087 / 4520 ( 90%)
.......F..................................................... 4148 / 4520 ( 91%)
```

**Comment by ishakhsuvarov** [comment]
@josh-carter Thanks for updating. Tests seem to "pass" this time. I'll try fixing the timeout issue, so we have a nice green check mark.

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2074) <br/>All committers have signed the CLA.

**Review by ishakhsuvarov — APPROVED** [review]

**Pull request merged**
