### PR TITLE
mageno/magento2#24212: Resolve Virtual Quote shouldn't display "Shipping & Handling" total when Create New Order 

### PR DESCRIPTION
**Pull request by engcom-Foxtrot**
### Description (*)

This PR fixes 2 MFTF tests ([commit](https://github.com/magento/inventory/commit/499e5aebd92d9b516f3967001975ee1833665003)). All other commits are from mainline.

### Fixed Issues (if relevant)

1. magento/magento2#24212: Resolve Virtual Quote shouldn't display "Shipping & Handling" total when Create New Order 

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2536) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2536) before we can accept your contribution.<br/>**2** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: danielrenaud<br/>:x: engcom-Foxtrot<br/>:x: zakdma<br/>:x: magento-engcom-team<br/>:x: bubasuma<br/>:x: sidolov<br/>:x: avattam06<br/>:x: dhorytskyi<br/>:x: buskamuza<br/>:x: lenaorobei

**Comment by ishakhsuvarov** [comment]
@magento run Integration Tests build

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento/inventory?pullRequest=2536) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento/inventory?pullRequest=2536) before we can accept your contribution.<br/>**3** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: VeronikaYarats<br/>:white_check_mark: engcom-Foxtrot<br/>:white_check_mark: danielrenaud<br/>:x: zakdma<br/>:x: magento-engcom-team<br/>:x: bubasuma<br/>:x: sidolov<br/>:x: avattam06<br/>:x: dhorytskyi<br/>:x: buskamuza<br/>:x: lenaorobei

**Comment by ishakhsuvarov** [comment]
Unfortunately mainline merge brings another issue with the integration test. Have to wait for solution before merging this fix.

**Comment by ishakhsuvarov** [comment]
SVC and Static Tests failures relate to the commits originating from the mainline

**Pull request merged**
