### PR TITLE
MSI-2018: Rename "Shipping Methods" to "Delivery Methods" in adminhtml

### PR DESCRIPTION
**Pull request by toddhainsworth**
### Description
Renames the "Shipping Methods" section of the admin to "Delivery Methods" now that MSI allows for store pickup.

### Fixed Issues (if relevant)

1. magento-engcom/msi#2028: Rename "Shipping Step" into "Delivery Method" on Magento Checkout

### Manual testing scenarios

1. Login to admin
2. Navigate to Store -> Configuration
3. Expand the 'Sales' section and note the renamed "Delivery Methods" section

### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2033) <br/>All committers have signed the CLA.

**Comment by maghamed** [comment]
hey @toddhainsworth ,

in the scope of MSI contribution, we are trying to avoid any changes of other Magento core files, which are not related to `Inventory*` modules.

Thus, if we need to customize / change something in the Core, there are two possible ways:
1. Create a separate Pull Request to the main Magento repository. But here we need to take into account that these changes should make sense even if Magento is installed without MSI. 
2.  Introduce a dedicated module with Inventory prefix, or use the existing one (like `InventoryInStorePickupAdminUi`) where we customize existing Core behavior.

**Comment by toddhainsworth** [comment]
Good call @maghamed 

I like the idea of using one of the existing Inventory* modules, I'll refactor the changes in this PR to be made from one of those modules.

**Comment by toddhainsworth** [comment]
@maghamed translations do not appear to be applying to the "Shipping Methods" label in the admin so I'm currently tackling that in the hopes of creating a new PR soon.

**Comment by rodrigowebjump** [comment]
@toddhainsworth I agree that Delivery Methods make more sense but changing it could get users confused since all instructions (including 3rd party) probably reffers to "Shipping Method" in admin section.

**Comment by ishakhsuvarov** [comment]
Hi @toddhainsworth

I'm closing this PR in favor of #2037 

Thanks!

**Pull request closed without merging**
