### PR TITLE
MC-34169: MSI Low Stock Report Grid Empty

### PR DESCRIPTION
**Pull request by arnobsh**
**MC-34169: MSI Low Stock Report Grid Empty**

### Description (*)

**ISSUE:**
Low Stock Report Grid is empty after creating a new out of stock product with 0 stock.

**STEPS TO REPLICATE:**

1. Install clean 2.3-develop + MSI
2. Create a new product with "Quantity > 0" and "Stock Status = In Stock" ("Out-of-Stock Threshold = 0")
3. Set the Quantity to 0 and leave the "Stock Status" dropdown "In Stock"
4. After saving, go to Reports > Low Stock Report and check that you can see the product in the "Low Stock Report Grid"
5. Reopen the product page in the backend: the "Stock Status" dropdown is "Out of stock" (expected behavior)
6. After saving the product again (with or without making any changes), go to Reports > Low Stock Report
**ACTUAL RESULTS:**
The grid is empty.

**EXPECTED RESULTS:**
The grid should show the product as it was shown it before the 2nd saving
### Fixed Issues (if relevant)

1. magento/inventory#MC-34169: https://jira.corp.magento.com/browse/MC-34169

### Questions or comments

**Reason:** The reason for showing the Low Stock Report Empty with zero quantity because when we set quantity zero the product automatically sets the status 'Out of Stock'. And 'Low Stock Report' only consider 'In Stock' status. For the first time, when we set the product with zero quantity, status does not get changed. After resaving it, it changed to 'Out of Stock'. That's why the issue happens. FOr the first time it shows in the report for the zero quantity and again if you visit the product and re-save with some data, then it disappears from the report.

**Proposed Solution:** If we want to show 'Low Stock Report' with zero quantity, we need to check the product status. So, proposed solution check, if the quantity os zero then it includes in the 'Low Stock Report' and for quantity greater than zero, it checks the status

**Regular CE edition:** Regular CE has the filter, to show zero quantity product with/without status check. That's why it appears in the report though the product is 'Out Of Stock'

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by arnobsh** [comment]
Running All Tests. Not ready to merge

**Comment by arnobsh** [comment]
@magento run all tests

**Comment by arnobsh** [comment]
@magento run all tests

**Comment by arnobsh** [comment]
@magento run <Functional Tests EE,Functional Tests CE>

**Comment by arnobsh** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by arnobsh** [comment]
@magento run Functional Tests B2B

**Comment by arnobsh** [comment]
@magento run Functional Tests EE,Functional Tests CE

**Comment by arnobsh** [comment]
@magento run Functional Tests EE,Functional Tests CE,Functional Tests B2B

**Comment by arnobsh** [comment]
@magento run all tests

**Comment by arnobsh** [comment]
Ready for Review

**Review by sidolov — APPROVED** [review]

**Comment by sidolov** [comment]
@magento run all tests

**Pull request merged**
