### PR TITLE
Delete test image after test execution

### LINKED ISSUE #1650: Fix AdminEnhancedMediaGalleryDeleteImagesInBulkTest
AC:
- unskip test
- test must pass

### PR DESCRIPTION
**Pull request by Nazar65**
### Fixed Issues (if relevant)

1. Fixes https://github.com/magento/adobe-stock-integration/issues/1650

### Manual testing scenarios (*)
MFTF tests passed

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Comment by Nazar65** [comment]
@magento run all tests

**Review by sivaschenko — APPROVED** [review]

**Comment by sidolov** [comment]
Failed test is not related to the changes, it's known issue: https://jira.corp.magento.com/browse/MC-33747

**Review by sidolov — APPROVED** [review]

**Pull request merged**
