### PR TITLE
Msi 1906

### PR DESCRIPTION
**Pull request by maghamed**
#1906 

#1919

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2009) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2009) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: maghamed<br/>:x: SergeyP18

**Comment by smoskaluk** [comment]
@maghamed @SergeyP18 
During testing of this PR I've found problem with return to stock after Credit Memo.

  Step to reproduce
Create fixed bundle with simple product as child
Place order for 5 items of bundle product
Partially invoice order for 3 items
Partially ship 3 items
Cancel order
Do Credit Memo with Return to stock on

  Result
Only 1 item of child simple product returned to source
image

  Wrong compestational reservation created for stock
image

**Comment by maghamed** [comment]
hey @SergeyP18  would you like to proceed with this PR further?

**Comment by ishakhsuvarov** [comment]
@maghamed @SergeyP18 I am closing this PR due to inactivity. 
Please feel free to reopen if you would like to proceed.

**Pull request closed without merging**
