### PR TITLE
Get rid of errors when running unit tests with Composer-based installation of Magento

### PR DESCRIPTION
**Pull request by orlangur**
… 

### Fixed Issues (if relevant)

1. https://github.com/magento/magento2/issues/5453

### Manual testing scenarios (*)

1. ...
2. ...

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds on Travis CI are green)

### CODE REVIEW

**Comment by magento-cicd2** [comment]
[CLA assistant check](https://cla.dev.magento.com/magento-engcom/msi?pullRequest=2092) <br/>All committers have signed the CLA.

**Comment by ishakhsuvarov** [comment]
Hi @orlangur 

Thank you for working on this. Could you please provide more details on this fix? Why is it targeting MSI only? Why this specific patch helps fixing the issue? 

Thanks

**Comment by orlangur** [comment]
```
Time: 1.24 minutes, Memory: 1832.00MB

There were 15 errors:

1) Magento\InventoryImportExport\Test\Unit\Model\ValidatorChainTest::testValidateWithOutValidators
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory-import-export/Test/Unit/Model/ValidatorChainTest.php:43

2) Magento\InventoryImportExport\Test\Unit\Model\ValidatorChainTest::testValidateWithOutErros
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory-import-export/Test/Unit/Model/ValidatorChainTest.php:43

3) Magento\InventoryImportExport\Test\Unit\Model\ValidatorChainTest::testValidateWithErros
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory-import-export/Test/Unit/Model/ValidatorChainTest.php:43

4) Magento\InventoryReservations\Test\Unit\Model\ReservationBuilderTest::testBuild
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory-reservations/Test/Unit/Model/ReservationBuilderTest.php:57

5) Magento\InventoryReservations\Test\Unit\Model\ReservationBuilderTest::testThrowValidationException with data set "with_missing_stock_id" (array('setSku', 'somesku'), array('setQuantity', 11))
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory-reservations/Test/Unit/Model/ReservationBuilderTest.php:57

6) Magento\InventoryReservations\Test\Unit\Model\ReservationBuilderTest::testThrowValidationException with data set "with_missing_sku" (array('setStockId', 1), array('setQuantity', 11))
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory-reservations/Test/Unit/Model/ReservationBuilderTest.php:57

7) Magento\InventoryReservations\Test\Unit\Model\ReservationBuilderTest::testThrowValidationException with data set "with_missing_qty" (array('setStockId', 1), array('setSku', 'somesku'))
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory-reservations/Test/Unit/Model/ReservationBuilderTest.php:57

8) Magento\Inventory\Test\Unit\Model\Source\Validator\CodeValidatorTest::testValidateCodeNotEmpty
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory/Test/Unit/Model/Source/Validator/CodeValidatorTest.php:37

9) Magento\Inventory\Test\Unit\Model\Source\Validator\CodeValidatorTest::testValidateCodeNotWithWhiteSpaces
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory/Test/Unit/Model/Source/Validator/CodeValidatorTest.php:37

10) Magento\Inventory\Test\Unit\Model\Source\Validator\CodeValidatorTest::testValidateCodeSuccessfully
ArgumentCountError: Too few arguments to function Magento\Framework\Validation\ValidationResultFactory::__construct(), 0 passed in /Users/orlangur/sites/m23composer/vendor/phpunit/phpunit-mock-objects/src/Generator.php on line 227 and at least 1 expected

/Users/orlangur/sites/m23composer/generated/code/Magento/Framework/Validation/ValidationResultFactory.php:29
/Users/orlangur/sites/m23composer/vendor/magento/module-inventory/Test/Unit/Model/Source/Validator/CodeValidatorTest.php:37

11) Magento\Reports\Test\Unit\Model\ResourceModel\Product\CollectionTest::testAddViewsCount
Error: Call to a member function create() on null

/Users/orlangur/sites/m23composer/generated/code/Magento/Catalog/Model/ResourceModel/Product/Collection/ProductLimitationFactory.php:43
/Users/orlangur/sites/m23composer/vendor/magento/module-catalog/Model/ResourceModel/Product/Collection.php:362
/Users/orlangur/sites/m23composer/vendor/magento/module-reports/Model/ResourceModel/Product/Collection.php:144
/Users/orlangur/sites/m23composer/vendor/magento/module-reports/Test/Unit/Model/ResourceModel/Product/CollectionTest.php:165

12) Vertex\Tax\Test\Unit\Observer\CreditMemoObserverTest::testSendRefundRequest
TypeError: Argument 1 passed to Mock_TaxInvoice_4013b25c::sendRefundRequest() must implement interface Vertex\Services\Invoice\RequestInterface, null given, called in /Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Observer/CreditMemoObserver.php on line 106

/Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Observer/CreditMemoObserver.php:106
/Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Test/Unit/Observer/CreditMemoObserverTest.php:144

13) Vertex\Tax\Test\Unit\Observer\InvoiceSavedAfterObserverTest::testNonDuplicativeInvoiceSentState
TypeError: Argument 1 passed to Mock_TaxInvoice_0a855715::sendInvoiceRequest() must implement interface Vertex\Services\Invoice\RequestInterface, null given, called in /Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Observer/InvoiceSavedAfterObserver.php on line 115

/Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Observer/InvoiceSavedAfterObserver.php:115
/Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Test/Unit/Observer/InvoiceSavedAfterObserverTest.php:176

14) Vertex\Tax\Test\Unit\Observer\InvoiceSavedAfterObserverTest::testSendOrderAfterInvoiceSaveRequest
TypeError: Argument 1 passed to Mock_TaxInvoice_0a855715::sendInvoiceRequest() must implement interface Vertex\Services\Invoice\RequestInterface, null given, called in /Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Observer/InvoiceSavedAfterObserver.php on line 115

/Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Observer/InvoiceSavedAfterObserver.php:115
/Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Test/Unit/Observer/InvoiceSavedAfterObserverTest.php:262

15) Vertex\Tax\Test\Unit\Observer\OrderSaveAfterObserverTest::testInvoiceSentAndActionsOccur
Error: Call to a member function create() on null

/Users/orlangur/sites/m23composer/vendor/magento/framework/Model/AbstractExtensibleModel.php:356
/Users/orlangur/sites/m23composer/vendor/magento/framework/Model/AbstractExtensibleModel.php:343
/Users/orlangur/sites/m23composer/vendor/magento/module-sales/Model/Order.php:2078
/Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Observer/OrderSavedAfterObserver.php:135
/Users/orlangur/sites/m23composer/vendor/vertex/module-tax/Test/Unit/Observer/OrderSaveAfterObserverTest.php:303

--

There was 1 warning:

1) Vertex\Tax\Test\Unit\Model\TaxQuote\TaxQuoteRequestTest::testTaxQuoteRequestCachedResponse
Trying to configure method "setStoreCode" which cannot be configured because it does not exist, has not been specified, is final, or is static

--

There were 5 failures:

1) Magento\Config\Test\Unit\Model\Config\Structure\ReaderTest::testReadWithValidationException
Failed asserting that exception of type "TypeError" matches expected exception "\Magento\Framework\Exception\LocalizedException". Message was: "Argument 1 passed to Mock_CompilerInterface_7ecb33f2::compile() must be an instance of DOMNode, null given, called in /Users/orlangur/sites/m23composer/vendor/magento/module-config/Model/Config/Structure/Reader.php on line 143" at
/Users/orlangur/sites/m23composer/vendor/magento/module-config/Model/Config/Structure/Reader.php:143
/Users/orlangur/sites/m23composer/vendor/magento/module-config/Model/Config/Structure/Reader.php:93
/Users/orlangur/sites/m23composer/vendor/magento/framework/Config/Reader/Filesystem.php:132
/Users/orlangur/sites/m23composer/vendor/magento/module-config/Test/Unit/Model/Config/Structure/ReaderTest.php:121
.

2) Magento\ProductVideo\Test\Unit\Controller\Adminhtml\Product\Gallery\RetrieveImageTest::testExecute
Expectation failed for method name is equal to 'getDirectoryWrite' when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.

3) Magento\Framework\Locale\Test\Unit\FormatTest::testGetPriceFormat with data set #1 ('de_DE', array(',', '.'))
Failed asserting that actual size 0 matches expected size 2.

/Users/orlangur/sites/m23composer/vendor/magento/framework/Locale/Test/Unit/FormatTest.php:82

4) Magento\Framework\Locale\Test\Unit\FormatTest::testGetPriceFormat with data set #2 ('de_CH', array('.', '''))
Failed asserting that actual size 1 matches expected size 2.

/Users/orlangur/sites/m23composer/vendor/magento/framework/Locale/Test/Unit/FormatTest.php:82

5) Magento\Framework\Locale\Test\Unit\FormatTest::testGetPriceFormat with data set #3 ('uk_UA', array(',', ' '))
Failed asserting that actual size 0 matches expected size 2.

/Users/orlangur/sites/m23composer/vendor/magento/framework/Locale/Test/Unit/FormatTest.php:82

ERRORS!
Tests: 21299, Assertions: 59740, Errors: 15, Failures: 5, Warnings: 1, Skipped: 116, Incomplete: 44.

---- /Users/orlangur/sites/m23composer/dev/tests/static/framework/tests/unit> /usr/local/Cellar/php@7.1/7.1.18/bin/php /Users/orlangur/sites/m23composer/./vendor/phpunit/phpunit/phpunit  

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

...............................................................................................                                                                                95 / 95 (100%)

Time: 283 ms, Memory: 4.00MB

OK (95 tests, 138 assertions)

---- /Users/orlangur/sites/m23composer/dev/tests/integration/framework/tests/unit> /usr/local/Cellar/php@7.1/7.1.18/bin/php /Users/orlangur/sites/m23composer/./vendor/phpunit/phpunit/phpunit  

PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

...........................................................................................................................................................S................ 172 / 181 ( 95%)
.........                                                                                                                                                                    181 / 181 (100%)

Time: 277 ms, Memory: 10.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 181, Assertions: 363, Skipped: 1.
----------------------------------------------------------------------
FAILED - 1 of 3:
 - /Users/orlangur/sites/m23composer/dev/tests/unit> /usr/local/Cellar/php@7.1/7.1.18/bin/php /Users/orlangur/sites/m23composer/./vendor/phpunit/phpunit/phpunit 
```

@ishakhsuvarov the only issue in core modules was in `Reports` but it is already fixed in `2.3-develop`. Other errors are in MSI modules and Vertex one. It happens due to unmocked factory constructor (I prefer `createMock` syntax over `getMockBuilder()->disableConstructor()`).

**Comment by ishakhsuvarov** [comment]
Thanks for the update

**Review by ishakhsuvarov — APPROVED** [review]

**Pull request merged**
